### ISSUE TITLE
Feature request: celluloid queue.

### ISSUE THREAD

**Issue by kostya** [celluloid/celluloid#100]
There is a need to call actor methods exactly one by one (like queue, 
because the methods doing something with state of the actor, and should not be crossed). 
Calls of the methods can happens asynchronously by some events.

Example actor:

``` ruby
class A
  include Celluloid

  def test(x)
    puts "test start #{x}"
    sleep 1
    puts "test end #{x} - #{Time.now}"
  end
end

a = A.new
a.test!(1)
a.test!(2)

sleep 3
```

The output is: 

``` shell
test start 1
test start 2
test end 1 - 2012-10-08 01:33:53 +0400
test end 2 - 2012-10-08 01:33:53 +0400
```

Not that needed.

I, also, can do this with futures:

``` ruby
class B
    include Celluloid

    def test(x, future = nil)
      future.value if future
      puts "test start #{x}"
      sleep 1
      puts "test end #{x} - #{Time.now}"
    end
end

b = B.new
f = b.future.test(1)
b.future.test(2, f)

sleep 3
```

The output is:

``` shell
test start 1
test end 1 - 2012-10-08 01:39:10 +0400
test start 2
test end 2 - 2012-10-08 01:39:11 +0400
```

Ok, but this is ugly, change the methods logic, and actor can have more methods.

I, also, try it with pool.

``` ruby
pool = A.pool(size: 1)
pool.test!(1)
pool.test!(2)

sleep 3
```

This is not work, minimal of the pool size is 2.
### So, the feature is:

```
queue = A.queue(:queue1)
queue.test!(1)
queue.test!(2)
```

Or

```
a.queue.test!(1)
a.queue.test!(2)
```

or

```
a.queue[:queue1].test!(1)
a.queue[:queue1].test!(2)
```

and output will be:

``` shell
test start 1
test end 1 - 2012-10-08 01:39:10 +0400
test start 2
test end 2 - 2012-10-08 01:39:11 +0400
```

Or, perhaps, there is a similar functionality, but I have not found the documentation.

**Comment by kostya** [comment]
Is there any way to implement queue methods within async methods, by patching actor mailbox? Because having one more actor for each actor is a memory cost. 

example:
```ruby
class A
  include Celluloid
  def for_queue
     sleep 1
     p 1
  end

  def not_queue
     sleep 1
     p 2
  end
end

a = A.new
3.times { a.queue :for_queue }
3.times { a.async :for_queue }

sleep
```

expected:
```
1
2
2
2
1
1
```

**Comment by tarcieri** [comment]
I think the correct abstraction here is something like `Celluloid::Channel`, which could also form the underpinnings of the mailbox...
