### ISSUE TITLE
Async/Future proxies are not easily testable

### ISSUE THREAD

**Issue by benlangfeld** [celluloid/celluloid#195]
Setting mock expectations on method chains is a pain in the ass. With bang syntax, it's easy:

``` ruby
foo.should_receive(:bar!).once.with(:baz)
```

With `#async`:

``` ruby
async_mock = mock('async proxy')
foo.should_receive(:async).and_return(async_mock)
async_mock.should_receive(:bar).once.with(:baz)
```

The tempting solution here is to create an rspec-mocks extension of some sort which allows the following syntax:

``` ruby
foo.should_receive(:bar).async.with(:baz)
```

But the thing that bothers me is that perhaps this is just covering up a bad smell. Thoughts?

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
