### ISSUE TITLE
Exception in #initialize took down parent SupervisionGroup

### ISSUE THREAD

**Issue by knewter** [celluloid/celluloid#233]
Detailed code and stacktrace here: https://gist.github.com/knewter/16f001cbdb533f386c6b

Had a discussion with @halorgium on IRC, he requested that I /cc @benlangfeld since it's supervision-related.

So there are at least a couple of wonky things happening here.  First off, I'm using a TaskThread because I have a recursive method that grows to a silly stack size, and I don't feel like changing it quite yet (most of the time I won't have a huge recursion stack, just on bootstrapping the data).

Secondly, I'm using net/http in the actor.  I'd rather use something celluloid::io based, but the `http` gem still has a few kinks to iron out it seems.

Thirdly, I was kicking things off in the `initialize` function.  @halorgium pointed out I could just do something like `async.start` to get out of the initialize, and my guess is that it won't take down its supervision group with that change, but he said this was odd behaviour anyway and indicative of a bug.

Let me know if I can provide any further details or testing.

**Comment by digitalextremist** [comment]
Moved to: celluloid/celluloid-supervision#6
