### ISSUE TITLE
Thread Pool never returns a Thread if shutdown has started

### ISSUE THREAD

**Issue by halorgium** [celluloid/celluloid#333]
If `InternalPool#shutdown` has been called, `InternalPool#get` will never return a `Thread`. 
This is because some of the `Thread`s have a status of `false` somehow. 

One of these `Thread`s is returned as `idle` and then rejected as dead because `Thread#status` is `false`. 
Infinite loop occurs.

**Comment by digitalextremist** [comment]
Still relevant @halorgium? Last activity 9/13.

**Comment by digitalextremist** [comment]
`InternalPool` has been depreciated. If this work on it is still needed, please reopen.

**Comment by e2** [comment]
@digitalextremist - I believe this affects the Spawner too - especially because of the assert_active in the get() method.
