### ISSUE TITLE
Extract latches from Celluloid::IO and Floss?

### ISSUE THREAD

**Issue by tarcieri** [celluloid/celluloid#341]
See:

https://github.com/celluloid/celluloid-io/issues/89
https://github.com/celluloid/floss/issues/23

Celluloid projects contain various one-off latch implementations. Perhaps we should unify them and make them part of Celluloid itself?

**Comment by digitalextremist** [comment]
@tarcieri are you still thinking this, or is this no longer relevant? Opened in 9/13.

**Comment by tarcieri** [comment]
Yes, I think at least Celluloid::IO's latch belongs in core.

**Comment by digitalextremist** [comment]
Will expect to extract and implement celluloid/celluloid-io#89 latch in `0.17.5` then.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
