### ISSUE TITLE
Changes to Celluloid::Mailbox handling

### ISSUE THREAD

**Issue by tobiassvn** [celluloid/celluloid#342]
As some of you might have read on Twitter, I have been playing around with alternative, JRuby-specific mailbox replacements over the past weekend. So far I've benchmarked the regular Celluloid::Mailbox against ArrayBlockingQueue and [LMAX Disruptor](https://github.com/LMAX-Exchange/disruptor). The results so far have been quite promising, with a roughly 350% increase in raw throughput when using Disruptor:

```
51200000 push/pop cycles
===============================================================
 
                         user     system      total        real
Disruptor            8.670000   0.150000   8.820000 (  8.564000)
ArrayBlockingQueue  13.040000   0.150000  13.190000 ( 12.961000)
Celluloid::Mailbox  30.090000   0.410000  30.500000 ( 29.894000)
```

Disruptor, due to it's lock-free nature also performs incredibly well in high-contention, multi-producer scenarios. ArrayBlockingQueue fails badly here:

```
9 producer thread(s), 1 consumer thread - 9000000 messages
=============================================================
 
                         user     system      total        real
Disruptor            9.330000   2.560000  11.890000 (  7.019000)
ArrayBlockingQueue   9.030000  10.430000  19.460000 ( 19.271000)
Celluloid::Mailbox   9.660000   4.480000  14.140000 (  9.546000)
```

Note that Celluloid::Mailbox and Disruptor are almost on par only because, I believe, we're hitting the limit of how fast a Ruby loop can pull messages out of the queue. Also, the performance is likely to improve (I spoke to @headius on Twitter about this yesterday) once the interaction with Disruptor is moved from Ruby to an annotated Java methods, which I didn't get around to do, yet.

Now, while it might be possible to use a Reactor class and EventedMailbox together, I think it'd be beneficial to use a regular Mailbox (sub-)class instead to minimize the amount of Ruby call frames, avoid having to buffer messages in a Ruby array and use Ruby-land mutexes. However, this is where I ran into an issue. Celluloid at the moment relies on Mailbox classes to include Enumerable to fetch messages of a certain type, which would obviously mutate the queue. From what I can see, most concurrent, lock-free queue data structures (including Disruptor) don't support this without some ad-hoc locking, which would obviously defeat the usage of a lock-free data structure in the first place.

Along with being able to use Disruptor, it would also open up other doors, like integrating with Akka mailboxes when running in a mixed Scala/Akka/JRuby environment (may be even the whole `akka.dispatch` infrastructure).

I wouldn't mind to get my hands dirty and implement the changes myself, but I'm not 100% sure about he best way and how feasible it is to make these changes to Celluloid.

**Comment by digitalextremist** [comment]
Where does this stand? Is it still relevant? It's from back in 10/13.

**Comment by digitalextremist** [comment]
I *believe* this was resolved by `SystemEvent` tasks moving to the front automatically. If not, reopen.
