### ISSUE TITLE
Condition can be signaled by other Conditions

### ISSUE THREAD

**Issue by halorgium** [celluloid/celluloid#343]
I'd like a cross-check on this. /cc @tarcieri 

Basically when the `Condition` is used in exclusive mode or in a normal `Thread`, the `Mailbox#receive` will return any `SystemEvent` messages. 
This means it potentially could be returned a `SignalConditionRequest` which is for the same `Thread` but a different `Condition`. 

[code](https://github.com/celluloid/celluloid/blob/a4a664925f96a60353631d9443f2564ea0e86b2e/lib/celluloid/condition.rb#L19)

**Comment by digitalextremist** [comment]
@halorgium is this still here? 10/13

**Comment by digitalextremist** [comment]
Please reopen this in `0.18.0` if there is still interest. It seems `Future` is still not `Condition` based, so whenever we do that it might be a good time to reincarnate this.
