### ISSUE TITLE
Support for dynamically removing SupervisionGroup members

### ISSUE THREAD

**Issue by Burgestrand** [celluloid/celluloid#355]
Supervision groups have a way of adding with [SupervisionGroup#add](https://github.com/celluloid/celluloid/blob/e306501fd6022bd8d02703aef5b67e0ab9319cc4/lib/celluloid/supervision_group.rb#L81). There is a way to access named members through the use of [SupervisionGroup#[]](https://github.com/celluloid/celluloid/blob/e306501fd6022bd8d02703aef5b67e0ab9319cc4/lib/celluloid/supervision_group.rb#L91) and calling terminate on that, but there’s a race condition there if the actor crashes when the termination is requested, and then restarted by the supervision group.

Being able to both add *and* remove would make supervision groups useful in situations where one would use multiple supervisors and managing members manually. At the moment supervision groups are mainly useful where you know the list of members will only grow, and never shrink.

Created from discussion in #340.

**Comment by digitalextremist** [comment]
Moved to: celluloid/celluloid-supervision#4
