### ISSUE TITLE
Release 0.16

### ISSUE THREAD

**Issue by tarcieri** [celluloid/celluloid#357]
`master` now contains a refactoring which separates `Celluloid::Cell` from `Celluloid::Actor`

It'd be great to release this soon, lest it langer on master without exercise from Celluloid users. I think this refactoring is important for Celluloid's future and maintainability.

There are some lingering issues we need to get resolved though. I don't know them offhand @halorgium, perhaps you could fill us in? :wink:

**Comment by digitalextremist** [comment]
This is long since done/past. Remainder is handled in #536 it seems.
