### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by tarcieri** [celluloid/celluloid#358]
We should release 1.0! While there's an awful lot of stuff we could potentially fix before shipping a "1.0" release, I think the biggest thing we can do is ship the `Actor`/`Cell` split as 0.16 (#357) and work to fix everything that breaks as a result :wink:

What about the rest of the stuff? Well, that's what 2.0 is for!

**Comment by digitalextremist** [comment]
With a lot having changed lately, and some soulsearching having happened regarding some refactoring projects needing done, here's a tentative schedule suggestion to get us up to `1.0` in achievable time:

https://groups.google.com/d/msg/celluloid-ruby/xUFSTGX1sKY/OoQI-jivoAIJ

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.

**Comment by digitalextremist** [comment]
@tarcieri, if we can get together a succinct list of what's included in this milestone, some of us can iterate on this over the Spring until it's finally done. Or did something specific prompt reopening?

**Comment by tarcieri** [comment]
I did a sweep of the open issues and closed this one accidentally

**Comment by arkhitekton** [comment]
All has been quiet in Gitter and here since January - has the second wind died down?  Are downloads still crazy high?  Is there hope of this being revived?

**Comment by tarcieri** [comment]
#789 is the place to start, unfortunately of all of the prospective interested people who said they'd triage that release, no one has seen it through so far

**Comment by digitalextremist** [comment]
I've been looking at the angle of reworking the actor system by implementing a `RINA` messaging system between actors. We also have an approved `Open Collective` organization. Am here, watching

**Comment by tarcieri** [comment]
I think the main thing Celluloid could benefit from, provided anyone wants to keep it going, is another release, followed by several other releases of minor changes and bugfixes.

Where things started to wrong before was with changes that were too invasive, creating too many bugs.

**Comment by digitalextremist** [comment]
Especially since I introduced most of those changes, I can start to budget a couple hours a week to `Celluloid` soon. Will start to make time as soon as I can
