### ISSUE TITLE
Retrieve actors from a pool.

### ISSUE THREAD

**Issue by meskyanichi** [celluloid/celluloid#360]
Is it possible to retrieve an array of actors from a pool? Something like:

```rb
pool = MyWorker.pool
pool.actors # => ....
```

I know supervisors have this functionality:

```rb
supervisor = MyWorker.supervise
supervisor.actors # => ...
```

**Comment by digitalextremist** [comment]
Moved to the gem's issue tracker. Continue there, if at all.
