### ISSUE TITLE
Task termination stack traces should be for the task being terminated, in order to determine why it had not completed

### ISSUE THREAD

**Issue by benlangfeld** [celluloid/celluloid#379]
Stack traces on task termination are somewhat useless, showing what is causing the task to be terminated (which is almost always actor shutdown). What I really want to know in these situations is what the task was doing in order to have required termination.

```ruby
def foo
  some_sync_call
  some_other_sync_call
end
```

With the info available:

```
[2014-01-30 14:09:26] WARN  Celluloid: Terminating task: type=:call, meta={:method_name=>:foo}, status=:receiving
```

it's impossible to tell if I was stuck at `some_sync_call` or `some_other_sync_call`, which may be the key to figuring out why the task ends up being terminated.

Not sure if this is even possible, but thought I'd throw the suggestion out there and get it recorded here.

**Comment by digitalextremist** [comment]
This seems long since resolved/bypassed. Closing, let me know if it's still an issue.
