### ISSUE TITLE
Supervision API is inconvenient and not fault resistant

### ISSUE THREAD

**Issue by jnicklas** [celluloid/celluloid#381]
Hi all, I wanted to kick off a discussion about something that's been bugging me when using Celluloid for a while. I feel that supervisors aren't as good as they could be. For one, the API is pretty inconvenient. Compare pools:

``` ruby
pool = SomeActor.pool(size: 5)
pool.async.some_method
```

With supervisors:

``` ruby
actor = SomeActor.supervise
actor.async.some_method # no method error
```

The Wiki suggests doing the following:

``` ruby
supervisor = SomeActor.supervise
actor = supervisor.actors.first
actor.async.some_method
```

This feels like a hack to me, and it also encourages saving a handle to the actor, which is a bad idea because it is not fault tolerant. A better option is to go through the registry:

``` ruby
SomeActor.supervise_as(:some_name)
Celluloid::Actor[:some_name].async.some_method
```

Unfortunately this is pretty ugly.

Also, it's impossible to avoid race-conditions with this API. Celluloid at this point makes no guarantee that the actor retrieved this way is alive, even though it is supervised. If the actor has recently died and I run the above code, I get a DeadActorError.

Supervisors could introduce (optional) buffering, and wait for the replacement actor to start in case it has recently died, instead of simply dropping the message. This is impossible to achieve without race conditions with the current API, as far as I can see.

So my suggestion is to make supervisors more similar to pools in their API. This would allow for an expansion in functionality which could make supervisors more fault tolerant, and it would make the code more consistent and easier to read. It would allow us to abstract away the fact that what we're dealing with is a supervised actor, rather than a regular actor.

**Comment by digitalextremist** [comment]
Will remember this during #511 and #550
