### ISSUE TITLE
Wrapping multiple objects with the same Cell

### ISSUE THREAD

**Issue by jnicklas** [celluloid/celluloid#386]
I'm not 100% sure I understand the Cell/Actor refactoring, but it's my understanding, that a Cell wraps an arbitrary object in an actor. I just ran into a situation where I'd like multiple objects to share the same Mailbox, basically because I don't want to put all methods on the same objects, since that wouldn't follow the single responsibility principle, but I also want it to be possible to pass the object off to another actor (or even a non-actor) and still preserve thread safety.

I did a pretty ugly workaround:

``` ruby
class Base
  include Celluloid

  def initialize(socket)
    @session = Session.new(self)
  end

  def schedule
    yield
  end
  execute_block_on_receiver :schedule
end
```

``` ruby
class Session
  def initialize(app)
    @app = app
    @app_actor = Celluloid::Actor.current
    @subscriptions = []
  end

  def subscribe(subscriber)
    @app_actor.schedule { @subscriptions << subscriber }
  end
end
```

Now `@session` can be passed to another actor, but it remains thread-safe, since it uses `Base`'s mailbox to prevent concurrent modification.

My thinking was that something like the following would be nice:

``` ruby
class Base
  include Celluloid

  def initialize(socket)
    @session = Cell.new(Session.new(self), Actor.current)
  end
end
```

``` ruby
class Session
  def initialize(app)
    @app = app
    @subscriptions = []
  end

  def subscribe(subscriber)
    @subscriptions << subscriber
  end
end
```

Now if we ever pass off `@session` to someone else, they'll be using `Session` encapsulated in a cell which uses the same mailbox as the current actor.

Reading the code, this actually shouldn't be too difficult to implement. I could take a stab at it if you guys think this is a sensible idea.

Of course, I haven't really thought this through, so it might be a totally terrible idea.

**Comment by digitalextremist** [comment]
@jnicklas is there interest in this issue? If not let's close it.

**Comment by jnicklas** [comment]
Not from my side, no. I don't really use Celluloid anymore. I don't know how the internals have changed since I last looked at this, at the time at least, it seemed to me that if the Actor/Cell split was ever completed than this feature should fall out of it pretty naturally, but maybe that hasn't happened. Don't keep this open on my account.

**Comment by digitalextremist** [comment]
@jnicklas thanks for the response on this -- I'll check back on it after an overall audit.
