### ISSUE TITLE
Support for Ruby 1.8 using backports gem

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [celluloid/celluloid#400]
Short:
Maybe use backports to support ruby 1.8.6+?
https://github.com/marcandre/backports

Long:
I am having troubles with Celluloid together with Rspec on Ruby 1.8 (which I unfortunately need to use). Somewhere in the celluloid timeline there was an api-breaking change on a 0.X or 0.0.X version, which is intended to be used for non-breaking feature additions / hotfixes only. This is probably why bundler and gems have problems when trying to install celluloid on ruby 1.8.

I believe that support for ruby 1.8 could easily be implemented with the backports gem (https://github.com/marcandre/backports). This way maybe we who are stuck in 1.8-land could enjoy some celluloid.

Forgive me if this has been addressed before, but I was not able to find that thread.

**Comment by digitalextremist** [comment]
Over a year old, feeling is *not* to support `1.8` and other EOL versions. Closing //
