### ISSUE TITLE
TaskThread for Sidekiq 3.0?

### ISSUE THREAD

**Issue by mperham** [celluloid/celluloid#403]
Sidekiq 3.0 is dropping MRI 1.9 support.  I've seen more reliability with TaskFiber in the past but that might have been due to 1.9 issues.  Should I switch to TaskThread for the 3.0 release and see how things go?

**Comment by digitalextremist** [comment]
@mperham: trying the repro is producing amazing unrelated errors and this seems ruled out in general, favoring `TaskFiber` instead. Closing, but if it's still a problem, let me know.
