### ISSUE TITLE
CurveZMQ Epoch

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#406]
I vote yes, pending discussion, on this for `16.0` ...

* celluloid/dcell#59
* celluloid/celluloid-zmq#35

This seems like an epoch to me, because of what can be done with just this feature coming in. The amount of traction for `Reel` in particular ( through `DCell` ), not to mention the upcoming suite of servers in discussions will benefit a lot. Cost can go down for massive clusters of cores, latency allowing... all in all this is _the thing_ needed for DCell to really flourish.

**Comment by digitalextremist** [comment]
@Asmod4n this seems defunct after what you've been working on, am I right? Doing some triage, trying to thin-out the issue tracker.

**Comment by Asmod4n** [comment]
yeah, and czmq is about to get official ruby bindings for the next release, so my wrapper won't receive any updates anymore: https://github.com/zeromq/czmq/tree/master/bindings/ruby/lib/czmq/ffi

**Comment by digitalextremist** [comment]
Ok, closing this and all associated issues elsewhere. Let's reapproach this once the bindings land.
