### ISSUE TITLE
Celluloid::Logger breaks existing code

### ISSUE THREAD

**Issue by ioquatix** [celluloid/celluloid#420]
Code expecting to get `::Logger` ends up getting `Celluloid::Logger` in specific contexts where celluloid has been included. This behaviour is unexpected.

https://github.com/celluloid/celluloid-io/issues/107

**Comment by digitalextremist** [comment]
@ioquatix do you have this covered, and if so are you able to get to it in the next few weeks?

**Comment by ioquatix** [comment]
This is still an issue.

**Comment by digitalextremist** [comment]
Yep. Working on it //

**Comment by e2** [comment]
:+1: - I wanted to suggest "internals" exactly myself. 

I'd also considered namespacing them though to match, e.g. `Celluloid::Internals::Foo` - a bit more complex in code, but it's also a clear distinction for contributors as to what constitutes "internals" and not.
Also, `Internals::Foo` isn't that bad/long really.

**Comment by digitalextremist** [comment]
@e2 that's how it's happening, right after `Celluloid::FSM` is out ( moments from now ) ... since that was so obvious and easy to ship.

**Comment by ioquatix** [comment]
Awesome :)

**Comment by digitalextremist** [comment]
Fixed at cfd06898ccbbe09cf295e63e92633c78ca54e255
