### ISSUE TITLE
Celluloid::Task::TerminatedError really StandardError?

### ISSUE THREAD

**Issue by ioquatix** [celluloid/celluloid#424]
Stopping an actor seems to sometimes result in Celluloid::Task::TerminatedError - but this often ends up going through the registered exception handlers since it is derived from StandardError. Wouldn't it make more sense for this to be derived directly from Exception and perhaps called "TerminatedException" - it isn't really an error condition right?

**Comment by digitalextremist** [comment]
I think @k-solutions is correct, if I understand, that this error type distinguishes between failure of an `Actor` and the failure of one `Task` ... in which case the error is resumable *from an `Actor` perspective*.

In any case, I am going to squelch the `Task::TerminatedError debug output unless `$CELLULOID_DEBUG` ... per the discussion in the google group.

**Comment by digitalextremist** [comment]
Reopen if needed, otherwise the thinking behind this has been lost to the sands of time.

**Comment by ioquatix** [comment]
I don't think the thinking behind this has been lost, it simply hasn't been clarified what is the correct behaviour. I'd still stand behind my original assertion and haven't seen clarification either way.

**Comment by digitalextremist** [comment]
@ioquatix what I mean is -- whatever the previous thought was, is lost in the sauce, because either its forgotten, or the system has moved to a point where it ought to be reassessed anyway. So it'd be better to step back and look at it, and make a decision on how it ought to be now, and experiment. I'm willing to test your idea and see where it goes, but that'd be more in the vein of a PR with a branch setup that way, and giving it a spin as a proposed change. I think that was suggested last year, May? Let's do that then.

**Comment by ioquatix** [comment]
Nothing has changed, this problem still exists, along with the duplicated `TimeoutError` classes. My original assertion still stands that `TerminatedError` should really be `TerminatedException` and not inherit from `StandardError`, unless it's something that should be implicitly caught by `rescue`.

I think that `TerminatedError` seems to imply that the termination was an error that occurred. Since I don't believe this is really correct interpretation of events, I think we should change it.

**Comment by tarcieri** [comment]
@ioquatix :+1:

**Comment by digitalextremist** [comment]
I've started on this, and have it mostly there -- in a separate branch -- so far something really funky is happening. Will figure out what it is.

**Comment by ioquatix** [comment]
@digitalextremist thanks for taking a decent look at this.

**Comment by digitalextremist** [comment]
No problem. You're right there's a lot of duplicated/fragmented exception/error code. I probably introduced problem myself, otherwise it'd probably be turnkey. Either that or its totally fubar.

**Comment by ioquatix** [comment]
I was thinking about this a bit more and wondering if `TerminatedException` is really the right name, because task termination isn't really an exceptional case, is it?

Perhaps `TaskTerminated` or something else might make more sense?

**Comment by digitalextremist** [comment]
We're on the same plane. That's what I called it.

**Comment by digitalextremist** [comment]
And just so it's no surprise to anyone. To my mind, it's not an `Exception` ... it's `SignalException`

**Comment by digitalextremist** [comment]
It's the equivalent of an in-process `Interrupt` ... but I didn't go that far and derive it from `Interrupt`, just the base class `SignalException` which this case seems to be.

**Comment by digitalextremist** [comment]
And for the record, the problem I'm experiencing is one I introduced. It has to do with method arity and the handling of `ArgumentError` ... reading through the `diff` log.

**Comment by TiagoCardoso1983** [comment]
About the duplicate TimeoutError, I remember I handled this in a PR that hasn't been accepted: https://github.com/celluloid/celluloid/pull/491/files . If I recall it correctly, the idea behind it was to extend non-celluloid errors like the standard TimeoutError with a ResumableError mixin so that the Fiber could be resumed nonetheless. I don't know if this could still be a valid approach, not only for the duplicated error classes, but also to the TerminatedException over there.

**Comment by digitalextremist** [comment]
Thank you for the history @TiagoCardoso1983! I am definitely experiencing turbulence unraveling and smoothing all this out. There are some serious ripple effects triggered by touching this code... Ah, I see your approach. Interesting

**Comment by digitalextremist** [comment]
I've sorted this mostly out, softly muttering "!iotquatix!" ... and I'm just getting strange `abort` behavior. And the "issue I introduced" was not really so -- it was needing to explicitly `rescue ::Exception` versus `rescue Exception` now that there's a `Celluloid::Exception` ... looking nearly done.

**Comment by ioquatix** [comment]
Redefining `Exception` is probably a REALLY bad idea since people are writing `include Celluloid` right?

**Comment by digitalextremist** [comment]
Very very good point. Everything else but the most important keyword I've varied to not clobber a global

**Comment by digitalextremist** [comment]
Ok I have a better word

**Comment by digitalextremist** [comment]
HAHAHAHAHA

That also fixed the `abort` issue.
No one ever needs to know this happened.

**Comment by digitalextremist** [comment]
So far, under `MRI`, there are thread crash errors coming out where there would have been `Task::TerminatedError` ... will see what I can do to mitigate that.
