### ISSUE TITLE
Feature: improved logging

### ISSUE THREAD

**Issue by ioquatix** [celluloid/celluloid#427]
I found this far more practical for debugging issues:

```
Celluloid.logger.formatter = proc do |severity, datetime, progname, msg|
    name = sprintf("%08x", Thread.current.object_id)
    if Thread.current.respond_to? :actor
        name = Thread.current.actor.subject.class.to_s
    end

    "#{severity[0...1]} [#{Time.now.strftime('%M:%S')}] #{name.rjust(30)}: #{msg}\n"
end
```

**Comment by digitalextremist** [comment]
We're coming up on a year. @ioquatix are you able to polish this off sooner than later?

**Comment by digitalextremist** [comment]
Bumping a version.

**Comment by e2** [comment]
Debugging and tracing in Celluloid should be reworked. I really want better debugging in Celluloid, so I might be working on it. 

(Currently, I have a horrible ocean of custom debugs, traces, dump() methods that I frequently *ehm* "rebase against" - all just to fix unit tests. This is madness).

There are plans to make `set_trace_func` be zero-overhead in JRuby, so hopefully there might be more complete tracing available without any performance impact for users who don't want it.

I even think that tracing should replace logging (and Probe) ... and logging should be handled by external gems. Celluloid simply needs a "strace" - and logging can be built on top.

**Comment by ioquatix** [comment]
Boop. I might take a look at this.

**Comment by digitalextremist** [comment]
@ioquatix I was going to put this together as [`celluloid-logger`](/celluloid/celluloid-logger) since I have like 4 loggers which each do the same thing differently right now. Care to put together a gem together?

**Comment by ioquatix** [comment]
@digitalextremist I'm actually working on celluloid-dns and so I don't have much available time between that and commercial work so if you are already planning on doing that, could you do it please and thanks?

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
