### ISSUE TITLE
supervisors_and_registry.rb doesn't seem to be working correctly

### ISSUE THREAD

**Issue by ioquatix** [celluloid/celluloid#430]
> ruby ./supervisors_and_registry.rb
	*** Demonstrating using the Supervisor API directly
	We should be in a clean state now: clean
	Brace yourself for a crash message...
	Uhoh, we crashed the actor...
	The supervisor should automatically restart the actor
	We should now be in a clean state again: clean
	*** Demonstrating using the actor registry
	We should be in a clean state now: clean
	Brace yourself for a crash message...
	E, [2014-05-24T17:30:08.083770 #22395] ERROR -- : Actor crashed!
	NameError: undefined local variable or method `oh_crap_im_totally_broken' for #<Celluloid::CellProxy(MyActor:0x80a2ddcc) @state=:dirty>
		./supervisors_and_registry.rb:16:in `broken_method'
		/Users/samuel/Documents/Programming/Internet/celluloid/lib/celluloid/calls.rb:26:in `public_send'
		/Users/samuel/Documents/Programming/Internet/celluloid/lib/celluloid/calls.rb:26:in `dispatch'
		/Users/samuel/Documents/Programming/Internet/celluloid/lib/celUhoh, we crashed the actor...
	The supervisor should automatically restart the actor
	luloid/calls.rb:63:in `dispatch'
		/Users/samuel/Documents/Programming/Internet/celluloid/lib/celluloid/cell.rb:60:in `block in invoke'
		/Users/samuel/Documents/Programming/Internet/celluloid/lib/celluloid/cell.rb:71:in `block in task'
		/Users/samuel/Documents/Programming/Internet/celluloid/lib/celluloid/actor.rb:362:in `block in task'
		/Users/samuel/Documents/Programming/Internet/celluloid/lib/celluloid/tasks.rb:55:in `block in initialize'
		/Users/samuel/Documents/Programming/Internet/celluloid/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
	D, [2014-05-24T17:30:08.180101 #22395] DEBUG -- : Terminating 7 actors...
	W, [2014-05-24T17:30:08.180710 #22395]  WARN -- : Terminating task: type=:exit_handler, meta={:method_name=>:restart_actor}, status=:callwait
		Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
	./supervisors_and_registry.rb:78:in `<main>': undefined method `state' for nil:NilClass (NoMethodError)

**Comment by sb8244** [comment]
Looks like a race condition in the actor being restarted. I pulled and it seems to fix it 100% of the time for me.

**Comment by digitalextremist** [comment]
Can still reproduce this.

**Comment by digitalextremist** [comment]
Moved to: celluloid/celluloid-supervision#3

**Comment by digitalextremist** [comment]
For posterity, I'll mention the cause and the workaround:

The `member.restart` call in `Supervision::Group#restart_actor` needed to be wrapped in `exclusive {}` otherwise `Member`'s assertion of `@actor = nil` zaps the entry in `@actors` ( and changing the entry in the registry is redundant, since the entry in in the registry *is* `@actor` ... but calling `member.restart` within an `exclusive` block solves this without any negative effects.
