### ISSUE TITLE
Calling async.run from base class constructor might not be a good design.

### ISSUE THREAD

**Issue by ioquatix** [celluloid/celluloid#434]
I know we discussed this briefly, but I'm wondering if it wouldn't be better for supervised actors to have some specific run method, similar to how finalisers are declared. If you think this is something useful to discuss, lets do so in this issue, otherwise lets close it and move on.

**Comment by digitalextremist** [comment]
@ioquatix we're coming up on a year on this -- how do you currently feel about this? Should this go into the supervision revamp coming up?

**Comment by digitalextremist** [comment]
Reopen if not solved in #511 or solved already.

**Comment by ioquatix** [comment]
Sorry, I didn't see your comments on this, there is so much noise that I wasn't reading all the email.

I believe this is still an issue. What is the work around?

**Comment by digitalextremist** [comment]
Above:

```ruby
supervisor = RubyDNS::RuleBasedServer.supervise(options, &block)
supervisor.actors.first.run
```

**Comment by ioquatix** [comment]
I don't mind that solution but I don't think it's ideal.

1/ It's cumbersome to write a lot and its a common enough pattern, such that having a specific way to have an actor "main" function might be a worthwhile abstraction.
2/ It's a bit of a pain for more complex things like supervisor groups and pools.

My gut feeling is telling me that we need a syntax like

```
class MyActor
    async_main :run
    def run
        ...
    end
end
```
