### ISSUE TITLE
TCPSocket connect_nonblock sometimes not working.

### ISSUE THREAD

**Issue by ioquatix** [celluloid/celluloid#436]
Getting the following error:

	Errno::EALREADY: Operation already in progress - connect(2) for 8.8.8.8:53
		/Users/samuel/.rvm/gems/ruby-2.1.2/gems/celluloid-io-0.15.0/lib/celluloid/io/tcp_socket.rb:85:in `connect_nonblock'
		/Users/samuel/.rvm/gems/ruby-2.1.2/gems/celluloid-io-0.15.0/lib/celluloid/io/tcp_socket.rb:85:in `initialize'

Perhaps we need to handle `Errno::EALREADY` in a similar manor to `Errno::EINPROGRESS` in `tcp_socket.rb`?

**Comment by digitalextremist** [comment]
@ioquatix you've released RubyDNS, so is this no longer an issue?

**Comment by digitalextremist** [comment]
Please reopen if this is unresolved, but if it is not resolved, it seems like `Celluloid::IO` and not `Celluloid`

**Comment by ioquatix** [comment]
Yes this is still an issue.

**Comment by digitalextremist** [comment]
@ioquatix right on -- seems `Celluloid::IO` related?

**Comment by ioquatix** [comment]
Yeah, I don't know why I originally put it here.

**Comment by ioquatix** [comment]
I believe the 2nd comment I made was an appropriate fix but it's been such a long time and it was one of the first bugs I reported, it then lead into the "ArgumentError: this IO is already registered with selector" which is a bug which spanned celluloid, celluloid-io and nio4r - a huge rabbit hole. This bug is relatively simple. It should be fixed. I didn't have the experience at the time to feel confident in making a PR because I didn't know if there were any side effects of my change.

**Comment by ioquatix** [comment]
Perhaps the first step is to write a failing spec. I wonder if the JRuby behaviour/hack is still required?

**Comment by tarcieri** [comment]
It's required for older versions of JRuby

**Comment by ioquatix** [comment]
Do we know what version it was fixed in?

Sometimes when I had bugs in older versions I'd have a separate file which would monkey patch the fix. Then, at an appropriate time in the future you'd just remove the file and the corresponding require. It means the main code path is fast for modern implementations and a fix is available for older implementations but the modern code path isn't messed up with lots of different hacks and it's easy to remove the hacks without spending a lot of time testing the code.

The only downside is really having a separate file in terms of maintenance but I actually see that as a plus because it makes the buggy functionality obvious.
