### ISSUE TITLE
Linking Actor to Actor pool. Not getting expected crash sequence.

### ISSUE THREAD

**Issue by keaplogik** [celluloid/celluloid#441]
```ruby
     supervisor = Celluloid::SupervisionGroup.run!
     # Used by the publisher to deliver the event.
      supervisor.pool EventDeliveryJob, as: :delivery, size: 5
      # Used by listener to publish packages.
      supervisor.supervise_as :publisher, EventShippingWorker, shipping_address
      # Listens for events on the queue.
      supervisor.supervise_as :listener, StompWorker, queue_uri, queue_name

      # Link workers and jobs so that each shutdown when one crashes.
      Celluloid::Actor[:listener].link(Actor[:publisher])
      Celluloid::Actor[:publisher].link(Actor[:delivery])
```

When actor publisher dies, listener dies
When actor delivery dies, publisher dies, and then listener dies.

Since I am pooling the delivery actor, when it raises an error, only that actor crashes and the linked actors do not.

If I do not pool the delivery actor, when it raises an error, all actors crash as well. This is what I expect.

Is linking to an actor pool not working?

**Comment by digitalextremist** [comment]
@keaplogik are you satisfied with the sequence of your actors crashing or does this prompt refactoring in your opinion?

**Comment by keaplogik** [comment]
Currently not working g on Celluloid project, but my opinion still stands that pooled actors should cause shutdown of other dependent actors. The work around for this case was to not pool the listeners and instead demonize the celluloid script over multiple processes. There were other issues we ran into with the stomp gem and celluloid so eventually backed out our celluloid implementation since there was little value without pooled actors in this instance.

**Comment by digitalextremist** [comment]
Thanks @keaplogik. If you feel up to posting an updated issue for resolution of this, please do that on the gem's issue tracker: http://github.com/celluloid/celluloid-pool/issues
