### ISSUE TITLE
Timer doesn't fire after some iterations

### ISSUE THREAD

**Issue by egnech** [celluloid/celluloid#443]
Here is my simple code.

``` Ruby
class Test
  include Celluloid
  def initialize
    @update_timer = every 0.1 do
      puts('.')
    end
    @default_unit_spawn_timer = every 2 do
      puts('!')
    end
  end
end

Test.new
sleep <-- added
```

But after some iterations (always different) timers stops and never fires again. What i did wrong?

PS. I'm using jruby 1.7.11 and celluloid 0.16.0.pre2

**Comment by zuk** [comment]
Not sure this is really fixed. I'm still experiencing `every` timers that stop firing for long periods of time. The problem seems to pop up mostly under heavy load, when I have several hundred actors all doing work. Once the load goes down, the `every` timer tends to start firing again.

**Comment by ioquatix** [comment]
@zuk I'd love to help but you are going to need to come up with a reproducible (within reason) test case otherwise I can't debug on my end.

**Comment by tarcieri** [comment]
@zuk are you sure you aren't executing some blocking operation that is stalling your actors?

DNS seems to have been a fun one of late: https://github.com/mperham/sidekiq/issues/2175

(Also note @ioquatix RubyDNS can be used to fix ^^^)

**Comment by zuk** [comment]
Yeah sorry I realize I'm not providing anywhere near enough details, but thought I'd raise the flag anyway. @tarcieri, that could very well be it — I'm not sure I have a full grasp on how Celluloid works yet, so I could be doing it to myself somewhere. However, I was under the impression that each actor runs on its own thread, so other actors shouldn't be stalling the actor employing the timer, and as far as I can tell there's nothing in the timer block itself that could be stalling things. I'll try to put together a better bug report at some point.

**Comment by tarcieri** [comment]
@zuk you can try `resolv-replace` as suggested in the Sidekiq issue, otherwise I'd suggest trying to put together a reproduction of the problem and opening a new issue.
