### ISSUE TITLE
Deadlock on long running MRI process using Celluloid

### ISSUE THREAD

**Issue by Who828** [celluloid/celluloid#445]
Hey,

We're are using Celluloid Pool Manager for one of our infra pieces. Today out of the blue the process got stuck, I had setup a signal trap to print out the back trace of all the threads but the process didn't respond to that or SIGTERM.

However I was able to able to get some information through GDB before it segfault,

1) Gemfile.lock and system infromation,
    https://gist.github.com/Who828/ef5fc41ac94c457a1a5b

2) Backtrace from gdb,
https://gist.github.com/Who828/f5e3c0ddd6e3ab137dd9

Do you require anything else? I am not sure what the problem is.
Any help would be appreciated.

**Comment by digitalextremist** [comment]
@Who828 is this still an issue for you?

**Comment by digitalextremist** [comment]
`celluloid-pool` has been extracted. If this is still an issue, please [post a bug report](/celluloid/celluloid-pool/issues/new) there.
