### ISSUE TITLE
Using Net::FTP with Celluloid

### ISSUE THREAD

**Issue by bmedici** [celluloid/celluloid#453]
Hi,

Trying to build a parralellized FTP client on Celluloid multi-threading, I have several problems. Whenever a transfer is started, the whole process is blocked until the transfer finishes.
Seems like Net::FTP is not "patched" by Celluloid's IO routines and not well supported in Actors.
What is the correct way to have many actors doing distinct file transfers and not blocking the whole process ?
Is Net::FTP planned to be included in Celluloid or Celluloid::IO ?
Thanks !

**Comment by digitalextremist** [comment]
@bmedici I am closing this. If you are still having trouble let us know.
