### ISSUE TITLE
0.16.1?

### ISSUE THREAD

**Issue by mperham** [celluloid/celluloid#457]
Sidekiq users have reported several showstopper bugs in 0.16.

1. Sidekiq no longer shuts down on TERM: https://github.com/mperham/sidekiq/issues/1929
2. Queues don't process quickly: https://github.com/mperham/sidekiq/issues/1937
3. Memory leak: https://github.com/mperham/sidekiq/issues/1934

I'll probably release 3.2.5 today which locks to 0.15.2.  In the meantime, please update this issue if there's a new release which I can smoke test for you.

**Comment by digitalextremist** [comment]
@mperham && @vangberg is this still an issue for you? We've got a `0-16-stable` branch right now, and we're moving forward to 0.17.0 ... unless there is a point release needed for Sidekiq or Adhearsion?

**Comment by mperham** [comment]
All good.

**Comment by digitalextremist** [comment]
Thanks @mperham
