### ISSUE TITLE
Custom exception handling in Celluloid Actor

### ISSUE THREAD

**Issue by perlun** [celluloid/celluloid#459]
Hi,

Is there a way to override the behavior of what happens on exception in a Celluloid Actor? When looking at this code, I get the impression that this is not the case: https://github.com/celluloid/celluloid/blob/master/lib/celluloid/actor.rb#L318

The reason I want to be able to inject some custom code is because I want all exceptions that occur to be logged to [Sentry](http://www.getsentry.com). Therefore, just letting the actor reboot is not really enough in my use case.

If this is indeed not supported, I am more than willing to contribute a PR that adds support for this. But please, share your thoughts about how it should be designed in that case, so we can get something done which is in line with the Celluloid philosophy in general. Thanks.

**Comment by digitalextremist** [comment]
@perlun if this is still an issue, please move it to the google group:

https://groups.google.com/forum/#!forum/celluloid-ruby
