### ISSUE TITLE
Best way to supervise an actor and use it without registry?

### ISSUE THREAD

**Issue by paddor** [celluloid/celluloid#467]
I've been doing something like this:

```ruby
class MyApp < Celluloid::SupervisionGroup
  supervise Foo, as: :foo
  supervise Foo::Bar, as: :foo_bar
end
```

The `Foo` actor would then be the only actor to make use of `Celluloid::Actor[:foo_bar]`.

Instead, I'd like to define my supervision group like this:

```ruby
class MyApp < Celluloid::SupervisionGroup
  supervise Foo, as: :foo
end
```

And then, in the Foo actor do this:

```ruby
class Foo
  include Celluloid
  def initialize
    @bar = Bar.supervise
  end
end
```

(Linking is not what I want, since I don't want `Foo` to restart when `Bar` crashes.)

The ugly thing is that now I have to use the `Foo::Bar` actor as follows:

```ruby
@bar.actors.first.my_method(:baz)
```

Is there a nicer way? I'm thinking of something like this:

```ruby
@bar.my_method(:baz)
```

**Comment by digitalextremist** [comment]
@paddor to get the response you're hoping for, please move this to the discussion group:

https://groups.google.com/forum/#!forum/celluloid-ruby
