### ISSUE TITLE
Feature request: Celluloid could shutdown faster after fork()

### ISSUE THREAD

**Issue by e2** [celluloid/celluloid#468]
I understand fork() renders Celluloid useless (in the child process).

I was just wondering if there was an elegant way for ActorSystem to detect that all the threads are dead, so mailboxes are dead, so there's no point in even calling actor.terminate! or actor.join.

(Found it while working on: https://github.com/rails/spring/pull/194)

How to preproduce:

```ruby
require 'celluloid'

Celluloid.logger.level = Logger::DEBUG
Celluloid.shutdown_timeout = 2

class Myactor
  include Celluloid
end

Myactor.new

Process.wait2 fork {}
```

**Comment by digitalextremist** [comment]
@e2 or @ioquatix can one of you land this in the next couple weeks?

**Comment by e2** [comment]
@ioquatix - I'm not sure about your use case. 

I've fixed the shutdown, but Celluloid is still in a pretty inconsistent/zombie state at that point (all the actor threads are dead at that point).

It would seem like Celluloid would have to be "supervised" and "restarted" when a fork happens, lol.

Seriously though, I'm not sure restarting by default is a good idea - probably depends on use case. Not to mention the work involved (to mark every class instance as a "zombie" and reboot).

@digitalextremist - could be merged into `0-16-stable` without risk (doesn't affect many people nor many possible scenarios)

**Comment by digitalextremist** [comment]
@e2 merged into master, submit another PR directly into `0-16-stable` if you feel it's important and can't wait until master is branched into a `0-16-5-stable` before GSoC ramps up.

**Comment by e2** [comment]
@digitalextremist - FYI @18a125e should be reverted (and fixed), because it breaks 10 tests in not-so-obvious ways

**Comment by digitalextremist** [comment]
@e2 please handle that separately in another ticket or find the ticket already there and @ me on it.
I can't revert based on "it breaks 10 tests in not-so-obvious ways" I need to see what you mean.

**Comment by digitalextremist** [comment]
@e2 thanks for all the tests by the way.

**Comment by e2** [comment]
@digitalextremist - you merged to master with 10 failing tests, so I explained why the tests failed (https://travis-ci.org/celluloid/celluloid/jobs/56209394#L676)

Thanks for merging this! (The more closed issues the better).
