### ISSUE TITLE
Supervision with custom Celluloid::ActorSystem

### ISSUE THREAD

**Issue by tobiassvn** [celluloid/celluloid#483]
It seems like currently only `Celluloid::ClassMethods.new` seems to respect a custom `Celluloid::ActorSystem` in `.actor_options`. When using `.supervise` or `.supervise_as` it falls back to `Celluloid.actor_system` unless you use a `ActorSystem#within` block. I'm not sure if that's intended behavior, but I through I'd point it out.

Example:

```ruby
require 'celluloid'
 
$actor_system = Celluloid::ActorSystem.new
 
class TestActor
  include Celluloid
 
  def self.actor_system
    $actor_system
  end
end
 
actor = TestActor.supervise_as(:foo)
 
puts $actor_system.running.include?(actor)
# => false
 
puts $actor_system.registered.include?(:foo)
# => false
 
actor = TestActor.supervise_as(:foo)
 
puts $actor_system.running.include?(actor)
# => false
 
actor = TestActor.new
 
puts $actor_system.running.include?(actor)
# => true
```

**Comment by tarcieri** [comment]
We don't support custom ActorSystems yet (and likely never will)
