### ISSUE TITLE
Raising Exception in pool causes mem leak

### ISSUE THREAD

**Issue by sb8244** [celluloid/celluloid#484]
Dug into https://github.com/mperham/sidekiq/issues/2107 and found it was a Celluloid issue. The issue arises from raising an Exception in a pool'd worker. The thread cleanup never gets run here: https://github.com/celluloid/celluloid/blob/a6584e787926de193b3aa64c70f03f125e3dc8cc/lib/celluloid/internal_pool.rb#L145

Here is a gist that recreates the issue with only Celluloid https://gist.github.com/sb8244/0a7e505dd1dafe432b31

So, is this a bug that should be fixed? I would love to contribute to Celluloid and can take a shot at this!

**Comment by tarcieri** [comment]
Can you figure out what sequence of events is causing an `Exception` to be raised before `clean_thread_locals` gets run? It gets called from here:

https://github.com/celluloid/celluloid/blob/a6584e787926de193b3aa64c70f03f125e3dc8cc/lib/celluloid/internal_pool.rb#L91

So that would indicate that it got raised between something returning an idle thread to the pool but before its thread locals were cleaned. That seems odd...

It seems like the simple solution is to immediately clear the thread locals as the first course of action.

**Comment by sb8244** [comment]
The Exception is getting run as part of the Worker. [Location here](https://gist.github.com/sb8244/0a7e505dd1dafe432b31#file-leak-rb-L27) in the gist

**Comment by sb8244** [comment]
If the Worker raises an `Exception`, then the `put(thread)` of `InternalPool` does not run

**Comment by tarcieri** [comment]
What prevents the thread from dying completely?

**Comment by sb8244** [comment]
Good question, I will research.

**Comment by sb8244** [comment]
I found it's not from the locals not being collected as there are only 10 threads and the number of locals in each is consistently single digits. However, there are a ton of ActorProxy objects left over (using Mass to detect objects in memory). Looking into the ActorProxy cleanup or why those references are still hanging around.

**Comment by sb8244** [comment]
Oh here we go. This is definitely the issue.

[InternalPool#create](https://github.com/celluloid/celluloid/blob/a6584e787926de193b3aa64c70f03f125e3dc8cc/lib/celluloid/internal_pool.rb#L130) does a rescue to say the thread crashed. Once this happens, a thread is put into the idle queue. However, `rescue` does not capture Exception in Ruby. So an idle thread does not get put into the queue and so `@all_threads` accumulates a bunch of dead threads that are not GC'd.

The solution is to `rescue Exception => ex` at InternalPool#create. However, many say that rescuing Exception is risky. I think it's probably acceptable in this situation because it is happening in an isolated thread.

**Comment by TiagoCardoso1983** [comment]
Rescuing Exception is indeed risky, I think it could potentially disable Ctrl+C, right? I would revert it. 

An alternative solution would be to "ensure" the thread is cleaned out. So, why don't you wrap the "put thread" line in an ensure block? What speaks against it?

**Comment by sb8244** [comment]
@TiagoCardoso1983 I'm thinking that is actually the best course of action:

https://github.com/celluloid/celluloid/pull/486#issuecomment-68614981
