### ISSUE TITLE
Question: SupervisionGroup doesn't prevent main thread finishing

### ISSUE THREAD

**Issue by Integralist** [celluloid/celluloid#487]
I'm using the following example code (taken from https://github.com/celluloid/celluloid/wiki/Supervision%20Groups):

```ruby
require "celluloid"

class Person
  include Celluloid

  def initialize(age, height, weight)
    p(age: age, height: height, weight: weight)
  end

  def bar
    rand(20)
  end
end

supervisor = Celluloid::SupervisionGroup.run!
supervisor.pool(Person, as: :people, args: [1,2,3], size: 3)

p "Size: #{Celluloid::Actor.all.size}"

2.times do
  p supervisor[:people].bar
end
```

If I don't include a `sleep` at the bottom of the file then the pool of Actors will all terminate.

I was under the impression that using a Supervision group would mean I wouldn't need to use `sleep` (i.e. https://github.com/celluloid/celluloid/wiki/Frequently-Asked-Questions#q-my-program-written-with-celluloid-just-exits-when-i-run-it-what-gives)

**Comment by tarcieri** [comment]
You have to have a topmost supervision group, and call `#run` on it (without the bang)

That code snippet was contributed to the wiki and appears to not be thread safe. It should probably be deleted.

**Comment by michal-kocarek** [comment]
Well that does not help. When I want to create the supervision group dynamically, I need to call .pool, .supervise, .supervise_as on existing supervision group which I cannot create with .run as it prevents call.

Is there any solution for that?

Also, this counts only with one supervision group, let's say I want to have two of them in the main thread, and wait for both of them to finish.

**Comment by tarcieri** [comment]
Generally I'd suggest using a supervision tree with a toplevel supervisor. Unfortunately Celluloid doesn't really have facilities for dynamic supervision trees right now. I don't believe Erlang or Akka have them either, however, and I'm not sure how they handle that problem.

Akka uses an explicit supervision system where actors automatically supervise their children, and you have to opt-out if you want to have an unsupervised actor.

**Comment by digitalextremist** [comment]
@michal-kocarek please continue this conversation on the google group: 
https://groups.google.com/forum/#!forum/celluloid-ruby

Or continue it here, on a closed ticket so we can do triage in the issue tracker.
