### ISSUE TITLE
[OT] - Thank you

### ISSUE THREAD

**Issue by elcuervo** [celluloid/celluloid#490]
**TL;DR**: Hello! This is an OT and useless issue

A lot of your projects are quite amazing. I used a lot of them in several projects and learnt a lot from them. You gave Ruby a lot of tools and technology that inspired the community in incredible and unexpected ways.

This is just my way to say thank you for the hard work, your impact in the community and the amazing ways you pushed the boundaries.

If I have the chance at some point I'd like to buy you a beer, a coffee or just give you a hug.

**Comment by tarcieri** [comment]
Thank you! Glad you like Celluloid :wink:
