### ISSUE TITLE
Celluloid::FiberStackError with Ruby 2.2 and Celluloid 0.16

### ISSUE THREAD

**Issue by ZipoKing** [celluloid/celluloid#492]
I'm using Sidekiq 3.3.1 which is using Celluloid 0.16 and last time I've started getting a lot of Celluloid::FiberStackError errors. It's not reproducable in all cases, i.e. sometimes when I'll restart Sidekiq job with the same parameters, it's making it's job done, and sometimes it throws this error.
Full stack trace:
>Celluloid::FiberStackError: stack level too deep (please see https://github.com/celluloid/celluloid/wiki/Fiber-stack-errors)
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:27:in `rescue in deliver'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:25:in `deliver'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:96:in `resume'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:359:in `task'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:67:in `task'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:59:in `invoke'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:34:in `block in initialize'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:38:in `call'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:38:in `call'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:19:in `handle_message'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:280:in `handle_message'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:154:in `block in run'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/timers-4.0.1/lib/timers/group.rb:52:in `wait'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:150:in `run'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
>        /opt/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'

**Comment by tarcieri** [comment]
This just means you've exceeded the stack size of a fiber. It's covered on the linked Wiki page:

https://github.com/celluloid/celluloid/wiki/Fiber-stack-errors
