### ISSUE TITLE
Extract pool into its own gem.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#512]
Attack the much feared extraction of `pool` into its own gem. This will be a massive breaking change on the same level as #511, so let's get this done in one swoop rather than causing people to need to heal their applications repeatedly.

**Comment by e2** [comment]
:+1:

**Comment by halorgium** [comment]
@digitalextremist #499 is not isolated to `PoolManager`, only exacerbated.

**Comment by digitalextremist** [comment]
@tarcieri, in the middle of the first pass of extracting pools. Ran into this:

https://github.com/celluloid/celluloid/blob/master/lib/celluloid/supervision_group.rb#L129

I'm thinking we need an optional set of procs to send into `Member`. That's better than the hackier way of aliasing out the real `Member` methods, overriding them, then calling the real one.. which wouldn't even work because this stuff needs to happen at a certain point. That era in `Reel` where we did that was just plain hell. So this way, when the pool is created, we inject `:initialize` and `:start` procs like so:

```
module Celluloid
  class SupervisionGroup
    class << self

      # Register a pool of actors to be launched on group startup
      def pool(klass, *args, &block)
        blocks << lambda do |group|
          group.pool(klass, prepare_options(args, :block => block))
        end
      end

    end

    def pool(klass, options = {})
      options[:method] = 'pool_link'
      options[:injections] = {
        # when it is a pool, then we don't splat the args
        # and we need to extract the pool size if set
        :start => Proc.new {
          if @pool
            options = {:args => @args}
            options[:size] = @pool_size if @pool_size
            @args = [options]
          end
        },
        :initialize => Proc.new {
          @pool = @method == 'pool_link'
          @pool_size = @options['size'] if @pool
        }
      }
      add(klass, options)
    end

    class Member
      attr_accessor :pool, :pool_size
    end

  end
end
```

And then within `SupervisionGroup`'s real definition:

```

    # A member of the group
    class Member
      # @option options [#call, Object] :args ([]) arguments array for the
      #   actor's constructor (lazy evaluation if it responds to #call)
      def initialize(registry, klass, options = {})
        @registry = registry
        @klass = klass

        # allows injections at initialize, start, and restart
        @injections = options.delete(:injections) || {}

        # Stringify keys :/
        @options = options.each_with_object({}) { |(k,v), h| h[k.to_s] = v }

        @name = @options['as']
        @block = @options['block']
        @args = prepare_args(@options['args'])
        @method = @options['method'] || 'new_link'

        @injections[:initialize].call if @injections[:initialize].is_a? Proc

        start
      end
      attr_reader :name, :actor

      def start
        @injections[:start].call if @injections[:start].is_a? Proc
        @actor = @klass.send(@method, *@args, &@block)
        @registry[@name] = @actor if @name
      end

      def restart
        @injections[:restart].call if @injections[:restart].is_a? Proc
        @actor = nil
        cleanup
        start
      end
```

**Comment by digitalextremist** [comment]
If that covers that, other than extracting Pool from the tests, I've got it out and I'm shaping the gem then.

**Comment by e2** [comment]
```ruby
@injections = options.dup.delete(:injections) || {}
```

Careful with mutation when extracting options ;)

**Comment by digitalextremist** [comment]
But I want to remove `:injections` from the hash, or I would have `fetch`'ed it... I don't want to cart `Proc`'s around anywhere outside `Member` brothaman.

**Comment by digitalextremist** [comment]
I'm going to break `0.17.0-prerelease` with this code without finishing fixing the tests ( not like they pass right now anyway ) so you guys can audit this big yank-out whenever.

**Comment by digitalextremist** [comment]
this has been cut:
* https://rubygems.org/gems/celluloid-pool
* repository: [celluloid-pool](/celluloid/celluloid-pool)

Feel free to test it.
/cc @tarcieri, @halorgium, @e2

**Comment by digitalextremist** [comment]
The code supporting this, and any other "SupervisionGroup Member Injection" is in `0.17.0-prerelease`

Any problems with the gem ought to be handled over there: [issues tracker](/celluloid/celluloid-pool/issues)

**Comment by e2** [comment]
@digitalextremist - I'll merge the changes/fixes I have for the pool when I get to it.
