### ISSUE TITLE
Get Travis tests working on jruby-head

### ISSUE THREAD

**Issue by e2** [celluloid/celluloid#525]
The main benefits:
- faster Travis total build completion (especially if timeouts are used in tests to prevent "hanging")
- exposing bugs before 1.x release (improved stability)
- possibly better debugging/testing facilities (given jruby schedules code very, very differently, Fibers are actually Java Threads, etc.)
- bisecting becomes possible (saved times discovering unintended side-effects of code changes)

Failing tests are a mixture of:
1. different thread/task info output (`:inspect`) - probably easy to fix (e.g. different regexps)
2. bugs in tests (Celluloid might need overhaul in this area regarding support for testing)
3. bugs in celluloid (racy stuff probably, or issues exposed by JRuby specifics)
4. bugs or incompatibilities in jruby/jruby-head (often hardcore to investigate - but worth fixing)

jruby-head may not seem like a "stable" idea, but then again if the JRuby team introduces a bug they don't detect, everyone benefits if a bad commit is quickly found in Celluloid tests.

**Comment by digitalextremist** [comment]
This is happening, except for use of `Group::Pool`
