### ISSUE TITLE
Audit feature branches and Pull Requests

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#529]
Purge outdated code, and/or recover valuable ideas.

**Comment by digitalextremist** [comment]
I've done about all I can for now until @halorgium especially has some time to go through his branches. Will come back to this when preparing the next release ( `0.18.0` ) after #545 is merged.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
