### ISSUE TITLE
Pool Manager : undefined method `times' for 1..2:Range

### ISSUE THREAD

**Issue by mistergibson** [celluloid/celluloid#541]
ruby ./gxg-www-reel.rb 
/var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:19:in `each': undefined method `times' for 1..2:Range (NoMethodError)
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:19:in `map'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:19:in `initialize'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
	from (celluloid):0:in `remote procedure call'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid.rb:180:in `new_link'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid.rb:208:in `pool_link'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/supervision_group.rb:141:in `start'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/supervision_group.rb:129:in `initialize'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/supervision_group.rb:85:in `new'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/supervision_group.rb:85:in `add'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/supervision_group.rb:81:in `pool'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
	from (celluloid):0:in `remote procedure call'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
	from /var/lib/gems/1.9.1/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	from ./gxg-www-reel.rb:120:in `<main>'

gxg-www-reel.rb source : https://gist.github.com/mistergibson/602183cdbb49e6ebbc17

**Comment by digitalextremist** [comment]
@mistergibson got it. Researching presently.

**Comment by digitalextremist** [comment]
First of all, you cannot spawn a pool of `Server` actors, because now you're binding the same port on the same network interface multiple times. What you want is to bind once, then hand off to a pool of request handlers. Refactor in that direction, then reopen.
