### ISSUE TITLE
Terminating task: type=:finalizer, meta={:method_name=>:__shutdown__}, status=:receiving

### ISSUE THREAD

**Issue by namit** [celluloid/celluloid#542]
I'm using Sucker Punch (which uses Celluloid) on Passenger. Every few hours, I get this in the logs:

D, [2015-04-03T17:06:00.016150 #25326] DEBUG -- : Terminating 3 actors...
W, [2015-04-03T17:06:00.016562 #25326]  WARN -- : Terminating task: type=:finalizer, meta={:method_name=>:__shutdown__}, status=:receiving
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.

Does this log mean that some tasks that I created through Sucker Punch get killed before completion because the underlying Passenger process was killed? From https://github.com/phusion/passenger/issues/1211 I understand that Passenger kills processes from time to time.

**Comment by tarcieri** [comment]
Probably. Also please ask questions like this on the mailing list.
