### ISSUE TITLE
Feature request: (thread) "safe" actor methods

### ISSUE THREAD

**Issue by e2** [celluloid/celluloid#548]
It would be nice to have "safe" properties on an actor.

Benefits: useful for both debugging and optimization

Methods marked as "safe" could be called on the Actor object directly - bypassing Celluloid. It would be up to the user to make sure those methods are really safe.

Use case 1: `#inspect` methods generally, which e.g. do not use thread-unsafe structures, like arrays or hashes.

Use case 2: `#tap` method (which probably should be specially handled in the proxy anyway)

Use case 3: `#busy_size` or `#name` - users should be able to skip Celluloid just to read a single Fixnum or immutable string

**Comment by tarcieri** [comment]
> Use case 1: `#inspect` methods generally, which e.g. do not use thread-unsafe structures, like arrays or hashes.

#inspect enumerates all instance variables. Any unsynchronized access to any shared mutable state is unsafe. There's nothing magic about arrays or hashes or non-arrays and non-hashes.

I am strongly opposed to bypassing the actor protocol for #inspect generally.

**Comment by digitalextremist** [comment]
Discussion/decisions here bumped a version.

**Comment by e2** [comment]
@digitalextremist - I've privately added a `Debugging.dump(obj)` method in specs to handle this somewhat. It tries to convert any Celluloid object into a string safely without side-effects.

So the debugging use case is pretty much solved if you assume people use unit tests (which means this debugging becomes available).

And since custom proxies could better handle this in production code, I'm closing this.
