### ISSUE TITLE
Add back support for supervision trees.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#562]
As per the novelle beginning in #557, detailing the pre-history era of Celluloid, circa the discovery of fire:

> In the before time, in the long long ago, before getting lost in the sands of time, calling `Celluloid::SupervisionGroup.run` would spawn the root of the supervision tree, and set this accessor to be the root of the supervision tree:

https://github.com/celluloid/celluloid/blob/master/lib/celluloid/supervisor.rb#L7

> Unfortunately grep confirms all of that code has been lost.

> Shutdown should start by checking if the supervision tree has a root, and if it does, terminating the root supervisor.

> `SupervisionGroup`'s walk their children, shutting them down in the reverse order they started in, and doing this synchronously:

https://github.com/celluloid/celluloid/blob/master/lib/celluloid/supervision_group.rb#L177

Movie renditions of novella ought to star Tom Hanks but somehow not copy the start/end of *Cloud Atlas*.

**Comment by digitalextremist** [comment]
`celluloid-supervision-tree` gem?

**Comment by tarcieri** [comment]
Maybe a `celluloid-supervisors` gem, factoring all of the existing supervision code out of core

**Comment by digitalextremist** [comment]
I was hoping you'd say that.

**Comment by digitalextremist** [comment]
That will radically simplify the test situation -- everything is so cramped. @e2 was talking about getting down to "bare bones" and hardening that, then gemming out the rest and I'm tending to think that way. With `celluloid-pool` gone *getting its own issues posted* it's a different feeling.

**Comment by digitalextremist** [comment]
And being able to pin dependencies on older versions of Celluloid versus newer versions of gems, would be tremendous. It's soundtrack would have to be *Court of the Crimson King* or something.

**Comment by digitalextremist** [comment]
AHHHHHHHHHHHHH AHHHH AH AHHHHHHHHH ( breathe ) AHHHHHHHHHHHHHHH AHHHHHhhhHHHHHHH AAAAAAhhHHHHHHHHH ( drum solo )

**Comment by digitalextremist** [comment]
Mostly done, tracked at own gem.
