### ISSUE TITLE
Extract FSM into gem.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#564]
With a simple search of the codebase, `Celluloid` itself isn't even using FSM. Only specs and examples use it. This seems natural to extract, for clarity.

**Comment by e2** [comment]
:+1:

**Comment by digitalextremist** [comment]
This is passing all tests, live at [celluloid/celluloid-fsm](/celluloid/celluloid-fsm), and cut onto rubygems.

**Comment by digitalextremist** [comment]
It could use some cleaning though, probably.

**Comment by ioquatix** [comment]
Nice work everyone.
