### ISSUE TITLE
Correctly avoiding "Dangerously suspending task" and related

### ISSUE THREAD

**Issue by e2** [celluloid/celluloid#565]
In a nutshell, there's no "recommended" way to do initialization which e.g. calls other actors synchronously. 

Given a "resource actor", e.g.:

``` ruby
resource = ResourceActor.new # provides get() method
```

users have to choose between:
##### 2-step-init (https://github.com/celluloid/celluloid/issues/434)

``` ruby
actor = HazResourceActor.new(resource)
actor.acquire_resource # avoid suspending #initialize
```
##### A convenient "shorthand" but potentially dangerous/bad design/etc.:

``` ruby
actor = HazResourceActor.new(resource) # calls resource.get(), gets warning
```
##### Some "magic" workaround

``` ruby
actor = HazResourceActor.new(resource) # resource.future.get()
actor.do_stuff # calls future.value to wait until ready
```
#### Impact:
- problems with base classes and supervisors (@ioquatix): https://github.com/celluloid/celluloid/issues/434
- warnings that people have no idea how to handle (@halorgium wrote the warning code): https://github.com/celluloid/celluloid/issues/283
#### Suggested solution:

Built in support for "2-phase initialization" via an "after_initialize" property (like @ioquatix suggested here for async methods: https://github.com/celluloid/celluloid/issues/434#issuecomment-91056263)

Something like this:

``` ruby
class HazResourceActor < SomethingElse
  include Celluloid
  after_initialize :get_resources

  def initialize(resource_container)
    @resource = nil
    @resource_container = resource_container
    super # just like in POR
  end

  def get_resources(resource)
     @resource = @resource_container.get
  end

  def do_stuff
    @resource.devour
  end

end
```

and then simply do:

``` ruby
actor = HazResourceActor.new(resource)
actor.do_stuff # resource guaranteed to be acquired by this point
```

This allow solving initialization problems with base classes (as long as people put the actual code in the after_initialize declared method).

The issue I have is that it's dumping a few more responsibilities on Celluloid.

Thoughts?

**Comment by digitalextremist** [comment]
This is very, very good research, and I believe an elegant approach akin to `:finalizer`, solving a very long standing problem, and probably/possibly well... *But* this also fits into the same category as #563 requiring conversation, probably putting it into `0.17.5` ... and just to emphasis, both this issue and that aren't unsolvable immediately, it's that not only will this touch high-churn code or introduces new conventions, it's the sort of thing that could end up making Celluloid unfamilar to its most veteran community members unless we do thorough documentation and stages of announcements *in the release before it* so now is the time to announce the decision, then the code would go into the next release.

**Comment by e2** [comment]
@digitalextremist - it's not a breaking thing, it's an "add-on" that simply saves the users from making 2 calls. It's so that users don't have to implement this themselves. 

"Syntactic sugar" if I may.

Currently, there's even no info on what to do when you get a "dangerously suspending" issue - I'm sure that by itself has frustrated and discouraged many users.

**Comment by digitalextremist** [comment]
I understand @e2. That much differentiates it from #563, but this will need to be well documented. Are you willing to take what you've started in the issue itself and make that into a Wiki page before the release? That much will allow people to rtfm in advance.

**Comment by e2** [comment]
> this will need to be well documented

That should happen after a working implementation, which should happen after an implementation is agreed upon (thus, the purpose of this issue).

To me, the documentation is first in the tests (there are many tests that trigger this warning, so there's no point in documenting now something Celluloid doesn't even properly do itself).

There's no use even attempting documenting or committing to it, if for some reason the implementation is postponed for months or years (for whatever reason).

(#564 discouraged me from even attempting to create a PR for this.)

**Comment by digitalextremist** [comment]
Well then in that case, discouragement aside ( not intended by #563 ) bringing out the idea first ( which is a good one ) is great -- so yes, `0.17.5` after the implementation code. I assumed you'd written it already since you'd usually implemented first, then discussed.

**Comment by ioquatix** [comment]
+1

**Comment by ioquatix** [comment]
Was any progress made on this?

**Comment by digitalextremist** [comment]
Been too busy but it's on my list for `0.17.5`

**Comment by ioquatix** [comment]
Where should I look to implement this?

**Comment by e2** [comment]
@ioquatix - what I'd do:
1. start with a test in actor_examples.rb (copy/adapt `:finalizer` specs)
2. implement the `:after_initialize` class method (as an option - just like with `:finalizer`)
3. probably do the same with a `:before_finalize` option (called before the finalizer)
3. ideally (optionally?), turn the warning into a failure (with a note/link about using 2-phase construction)
4. small wiki entry?

You can ping me for a PR/review (I don't watch Celluloid anymore).

**Comment by e2** [comment]
Forgot to add: and some edge case tests - like using this with inheritance. Also, likely some Celluloid tests themselves will have to be changed to use 2-phase (which is why I propose turning the warning into errors - definitely during running specs).

**Comment by ioquatix** [comment]
@e2 thanks for this it's really helpful, I'll see if I can get some time to implement it.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
