### ISSUE TITLE
Polish `InternalPool` as a viable albeit non-default alternative to `Spawner`

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#568]
During `0.17.0` the recently displaced `InternalPool` became `Group::Pool` and lost its place as the sole and therefore default collection of threads used by `ActorSystem` and associated things like `Future`, etc. Basically any thread `Celluloid` needs.

Let's give it a rest and basically leave it as it is for `0.17.0` ( i.e. less awesome, troublesome, etc ) and revisit it as a viable alternative in `0.17.5`.

**Comment by digitalextremist** [comment]
To actively discourage putting time into `Group::Pool` right now, it has been removed as a CI test case until we get into this issue later.

**Comment by e2** [comment]
@digitalextremist - it's green, but not wrapped up yet. See: https://github.com/celluloid/celluloid/issues/579

**Comment by digitalextremist** [comment]
Yeah I'm catching intermittent failures, but only on `jruby-head` and `rbx-2` at present. At gym, will look further soon.

**Comment by digitalextremist** [comment]
@aayushranaut this is a good one to look through, it would give you insight into the actor system itself.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
