### ISSUE TITLE
add a Celluloid::Probe.stop() method

### ISSUE THREAD

**Issue by e2** [celluloid/celluloid#573]
For me, this is so tests can shutdown cleanly without spamming the logs with actor crashes, fanout notification failures, etc.

Depends on: https://github.com/celluloid/celluloid/issues/355

**Comment by digitalextremist** [comment]
@e2 this, I am a big fan of :+1:

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
