### ISSUE TITLE
Registry losing actors.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#576]
This is likely a supervision issue, but in case it's not I'm starting here first... and either way, this affects usage of `Celluloid::Actor[]` ... working on reproductions, but not seeing consistent failure/success yet.

**Comment by e2** [comment]
@digitalextremist - beware - registry appears twice in the Celluloid tree (the 0.17-x branch with logging/namespace thing). And as far as I know, actors can be "renamed" accidentally through the registry (via a NamingRequest).

**Comment by digitalextremist** [comment]
@e2 that got cleaned out yesterday?

**Comment by e2** [comment]
@digitalextremist - how was I supposed to know?

**Comment by digitalextremist** [comment]
Revision of problem: Items are stored, but somehow they are being cleared from the registry.

**Comment by digitalextremist** [comment]
Something @niamster did in #585 resolved this!
