### ISSUE TITLE
Remaining classes not conforming to naming convention.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#577]
Per the sort of naming we established in `Reel`, i.e. `Server::PROTOCOL` versus. `PROTOCOLServer`, with the associated filesystem clarity of `reel/server/http` and `reel/server/https`, etc... versus `reel/http_server`, etc... the following was recently changed:

* `TaskFiber` was transitioned to `Task::Fibered`
* `TaskThread` was transitioned to `Task::Threaded`
* `EventedMailbox` was transitioned to `Mailbox::Evented` ( most recent )

Similarly there is the `Group`, well, group:
* `Group::Spawner` at `group/spawner`
* `Group::Pool` at `group/pool`

And now, finally, `Internals`:
* `Internals::CallChain`
* `Internals::CPUCounter`
* `Internals::Handlers`
* `Internals::Links`
* `Internals::Logger` ( fixes #420 )
* `Internals::Method`
* `Internals::Properties`
* `Internals::Receivers`
* `Internals::Registry`
* `Internals::Responses`
* `Internals::Signals`
* `Internals::StackDump`
* `Internals::TaskSet`
* `Internals::ThreadHandle`
* `Internals::UUID`

---

This leaves two glaring sets of inconsistencies, as follow. It seems...

#### Proxies ( this is probably the worst, with every file being `proxies/type_proxy.rb` )
* `AbstractProxy` ought to be `Proxy::Abstract` and exist at `proxy/abstract.rb`
* `ActorProxy` ought to be `Proxy::Actor` and exist at `proxy/actor.rb`
* `AsyncProxy` ought to be `Proxy::Async` and exist at `proxy/async.rb`
* `BlockProxy` ought to be `Proxy::Block` and exist at `proxy/block.rb`
* `CellProxy` ought to be `Proxy::Abstract` and exist at `proxy/cell.rb`
* `FutureProxy` ought to be `Proxy::Abstract` and exist at `proxy/future.rb`
* `SyncProxy` ought to be `Proxy::Abstract` and exist at `proxy/sync.rb`

#### Calls ( similar to the makeup of `Task`, which now conforms to convention )
* `AsyncCall` ought to be `Call::Async` and exist at `call/async.rb`
* `BlockCall` ought to be `Call::Block` and exist at `call/block.rb`
* `SyncCall` ought to be `Call::Sync` and exist at `call/sync.rb`
* `Call` ought to exist at `call.rb` ( not `calls.rb` ) and be required before the above.

Since there are cascading changes going out to `Celluloid::IO`, all the gems, `Reel`, etc... might as well as cover this now, unless it's going to totally ruin someone's mind. The above are the *only* offending classes/files, then we're completely consistent across the board, except how `Celluloid::IO` does not use `IOType/server` then `IOType/socket` if not just `IOType`.

/cc: @tarcieri

**Comment by e2** [comment]
@digitalextremist - changes like this should be very fast and atomic, because it makes merging difficult. 

It's almost like putting a mutex lock on the repository, so:

- if you want to change "everything", do it quickly, so the patches can be rebased sooner (these changes may make almost all current PRs unmergable)
- if you need more time, break it up into smaller commits (start with uuid, for example, make it work, then move on to the next class) - this makes merging more managable later on
- or, you can "postpone" the merge until everything is finished - but then there's a lot of error-prone merging (where changes can get lost) either for you and/or for everyone else

I'm not against the changes - just against them "pending" or "in progress" or worst of all "half finished" for too long.

(I already may have lost pending fixes - for code extracted out of Celluloid into gems).

**Comment by digitalextremist** [comment]
This will be fast. And the files will be renamed not duplicated or removed. The `Internals` change I took over in the middle after trouble like you mention, so this would not be that way.

**Comment by e2** [comment]
@digitalextremist - in that case, I'll be waiting for you to let me know, so I can rebase+merge.

I'm currently reworking spec helpers - let me know if any major conflicts/failures come up on my abstractive/e2-experimental branch.

**Comment by digitalextremist** [comment]
@e2 I'll do it in like 8-10 hours unless there are objections to the convention.

**Comment by e2** [comment]
@digitalextremist - I've rebased my changes to celluloid/0.17.0-prerelese. This stuff is mostly to harden the specs, but it seems ok. I have more coming, but I'll keep in mind the changes.

**Comment by e2** [comment]
@digitalextremist - there shouldn't be any objections to the convention. If people want the old classes, you can always do:

```ruby
module Celluloid
  Logger = Internals::Logger
end
```

And you can wrap those in a `deprecated.rb` file, which you can simply remove for 1.x.

**Comment by digitalextremist** [comment]
This is complete, and pushed to the prerelease branch.

**Comment by e2** [comment]
Thanks!
