### ISSUE TITLE
Announce 0.17 pre/rc

### ISSUE THREAD

**Issue by ioquatix** [celluloid/celluloid#578]
Can we please track 0.17 rc issues here so I can also do some testing on my end?

I'd like to test RubyDNS with 0.17 rc so I know that everything is still working on my end. I'm sure that I'm not the only one (e.g. sidekiq).

Alternatively if there is a better way to do this feel free to suggest or improve :)

**Comment by e2** [comment]
@digitalextremist keeps things well organized AFAIK - https://github.com/celluloid/celluloid/milestones/0.17.0

For keeping track of production-related changes, just do a `git diff` on the `lib` dir - very few changes to review (which makes 0.17 less likely to have issues).

**Comment by ioquatix** [comment]
Okay the milestone makes sense but I guess when the time comes to test the rc where will it be announced?

**Comment by e2** [comment]
@ioquatix - good point. Probably best to change this issue's title to "Announce 0.17 pre/rc" or something.

**Comment by digitalextremist** [comment]
The changelog will be broadcast on Google groups as usual, when `pre1` is cut and testable ( with the milestone of closed issues there too ) ... only once tested at `pre1` for a while will the actual release go live. Generally it's also announced on Twitter, in IRC, I even post status updates to LinkedIn and share that with known contributors and dependents. This won't be sudden, undocumented, and quiet :)

**Comment by ioquatix** [comment]
I'm subscribed to that group but I don't get notifications.. perhaps it would be good to have something here?
