### ISSUE TITLE
Disabling Actor#kill on JRuby and Rubinius

### ISSUE THREAD

**Issue by e2** [celluloid/celluloid#582]
Background: Actor#kill is pretty dangerous, since it calls Thread#kill on the Actor thread. This can potentially kill the thread while it's waiting to get a mutex lock ... which results in pretty bad JRuby/Rubinius exceptions (ConcurrencyError, Lock errors) - something users won't expect (and errors Celluloid can do nothing about).

Also, Actor#kill can kill finalizers and initializers, leaving them in a non-deterministic state. It also prevents Actor#terminate from being predictable (e.g. if linking is involved). It can cause a torrent of DeadActorError occurrences in various areas. The Actor's tasks can become "orphaned" and they can crash on sync calls, timeout, etc.

In fact, if existing JRuby projects get a NoMethodError on Actor#kill ... it's actually the least dangerous and least frustrating solution I can think of.

(If users seriously want to to kill an actor thread, they should add a method to their actors to expose Thread.current - and they can kill it anyway if they want).

@tarcieri, @digitalextremist  - if you have no objections, I'd like this added to 0.17. It's a breaking API change for JRuby projects, yes. But a very good one IMHO.

**Comment by e2** [comment]
@digitalextremist - I've added it here: https://github.com/celluloid/celluloid/pull/580

**Comment by digitalextremist** [comment]
For the time being, `kill` is disabled except under `mri` then. Might want to have this wrapped in something that doesn't solely base it off which ruby is being used, but more of a configuration option of `safety` is `on` or `off` and default to `on` as it is now.

**Comment by e2** [comment]
@digitalextremist - for the time being, I'd leave it for backward compatibility. It is actually MRI specific - neither JRuby nor Rubinius make any guarantees about how `kill` works, while MRI is single-threaded, so this is ok.

Ideally, it should be removed from MRI as well - but that's in the area of compatibility/releases, so I'm leaving it up to you guys. 

(I'm caring about MRI less and less here - keeping JRuby working seems like a saner strategy for the sake of development/improvement).
