### ISSUE TITLE
The Rake `:benchmark` task fails (Pool was removed)

### ISSUE THREAD

**Issue by e2** [celluloid/celluloid#583]
The failure is on Travis: https://travis-ci.org/celluloid/celluloid/jobs/58674445#L643

(Though, I'm unsure if the benchmarks are even worth running on Travis).

I think benchmarks should be part of a "release" task (a new Celluloid gem version shouldn't be released if there's a big performance drop).

I think an "ideal" benchmark would compare the current version of Celluloid with a previous version.

**Comment by digitalextremist** [comment]
https://travis-ci.org/celluloid/celluloid/jobs/58838248#L610

Resolved by creation of `celluloid-extras` gem and movement of `Rehasher` out of the pool example into `Celluloid::Extras::Rehasher`

3fc6e7bec940f04bdf1be27897327bf147285d63
