### ISSUE TITLE
Write call retry tests.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#591]
- [ ] Create a test for the case of issuing a `Call` which will fail at first due to `TimeoutError` but then be retried and succeed.
- [ ] Create a test for the case of issuing a `Call` which will fail at first due to `TimeoutError` but then be retried and fail more than the number allowed, then raise `TimeoutError` for the caller.

( In certain cases, a supervisor must instantiate & link an actor that takes longer than 5 seconds to launch, so the supervisor ends up crashing without a chance. Ideally for supervision cases, this allowed number of call retries can be configured to be infinite and it'd just spam error output with warnings/errors. This way, in the future if the actor could not launch due to something being unavailable for example, as soon as it _is_ available, the actor reappears. )

**Comment by digitalextremist** [comment]
Adding this behavior will come in the next release.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
