### ISSUE TITLE
Since kill is gone ( except in MRI ) shutdowns raise NoMethodError

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#592]
https://travis-ci.org/celluloid/celluloid/jobs/59063051#L690
```
NoMethodError: undefined method `kill' for Celluloid::Actor:Class
           shutdown at /home/travis/build/celluloid/celluloid/lib/celluloid/actor_system.rb:99
               each at org/jruby/RubyArray.java:1613
           shutdown at /home/travis/build/celluloid/celluloid/lib/celluloid/actor_system.rb:97
           shutdown at /home/travis/build/celluloid/celluloid/lib/celluloid.rb:168
  register_shutdown at /home/travis/build/celluloid/celluloid/lib/celluloid.rb:160
```

**Comment by e2** [comment]
I didn't get to finish this (default Reaper).

Basically, on JRuby and Rubinius there shouldn't be anything where the kill() is - if terminate didn't work, shutting down the group is the only option (anything else requires complex logic to detect whether the actor is being finalized, if it's running, if it can be queued for joining later, etc).

The join code OTOH should be something like this (in JRuby/Rubinius):

```ruby
Timeout.timeout(timeout) do
  begin
    Actor.join(actor) # optionally with a timeout parameter
  rescue => ex
    Celluloid::Logger.warn("Actor failed to terminate cleanly: #{ex}")
  end
end
```

(You want to give each actor time to finish - you don't want the first one stuck to prevent the others from terminating+finalizing without being given a chance to show failures, etc.). The timeout isn't honored (worst case for e.g. 15 actors it will be 15 x timeout), but generally other actors will finish terminating while one is waiting for the timeout.
