### ISSUE TITLE
Celluloid::Future explicit signalling issue

### ISSUE THREAD

**Issue by stavro** [celluloid/celluloid#603]
I'm having troubles with the usage of `Celluloid::Future` to allow awaiting on the result of a Celluloid workload.

Psudocode:

```ruby
future = Celluloid::Future.new
future.signal(1234)
future.value #=> NoMethodError: undefined method `value' for 1234:Fixnum
```

A workaround:

```ruby
future = Celluloid::Future.new
future.signal(Struct.new(:value).new(1234))
future.value #=> 1234
```

What am I doing wrong?  *Must* futures be invoked as a method enhancement (`actor.future.method_name`) or with a block (`Celluloid::Future.new { do_work }`)? Or should they be able to be used explicitly as indicated above?

**Comment by digitalextremist** [comment]
@stavro are you trying to *signal* the `Future` above? Maybe describe what you expect?

**Comment by stavro** [comment]
I would expect calling `.value` on a `Celluloid::Future` to either block the calling thread or return the final value immediately .. instead I see a `NoMethodError`

**Comment by digitalextremist** [comment]
Well yeah, `value` is being called on `1234` ... that's a `NoMethodError` caused at `Result#value` not `Future#value`

**Comment by tarcieri** [comment]
You shouldn't use `Celluloid::Future` like that directly. You either need to give it a block, or call the `#future` method on an actor proxy

**Comment by digitalextremist** [comment]
https://github.com/celluloid/celluloid/blob/master/lib/celluloid/future.rb#L102
https://github.com/celluloid/celluloid/blob/master/lib/celluloid/future.rb#L137

**Comment by digitalextremist** [comment]
Please let us know if you have any problems. So far `celluloid` is behaving properly and you're getting `NoMethodError` from `Celluloid::Future::Result` as designed.
