### ISSUE TITLE
last stable release in v0.16?

### ISSUE THREAD

**Issue by niamster** [celluloid/celluloid#610]
I propose to have a stable release in 0.16 branch. That is to have external gems to depend on precise version rather than follow master all the time if they want some features and happy with _current_ master.

**Comment by tarcieri** [comment]
Myself or @digitalextremist can do a release of the https://github.com/celluloid/celluloid/tree/0-16-stable branch as soon as all relevant commits have been cherry-picked onto it. Are there things you want in another 0.16 release that aren't presently on the https://github.com/celluloid/celluloid/tree/0-16-stable branch?

**Comment by niamster** [comment]
I don't have anything in mind. I just want to have a stable release of dcell before it moves to 0.17.

**Comment by tarcieri** [comment]
I propose we release `0-16-stable` as 0.16.1.pre then and request that Sidekiq users test it.

**Comment by mperham** [comment]
@tarcieri As long as you start with Square.  :-P

**Comment by tarcieri** [comment]
:smile: I can try eating our own dogfood there first

**Comment by digitalextremist** [comment]
Would it be OK with the world if we did this *after* getting `0.17.0` to prerelease? With that, there's the hardening of `0.17.0` itself, but also the `backported` version of that prerelease. Doing a `0.16.0` stable will effectively be 3 releases. I'm good with this, but it'd be nice if we cherry picked once the next release is able ready, rather than adding another step *before* `0.17.0` is ready to cut an RC of.

**Comment by niamster** [comment]
I don't mind if it be out after 0.16.

**Comment by digitalextremist** [comment]
You mean `0.17.0` right?

I am asking that we do this:

1. `0.17.0.rc1` ( no backport mode )
2. `0.17.0.rc2` ( with backport mode )
3. `0.16.1.pre1` ( as requested here )
4. `0.17.0` ( final )
5. `0.16.1` ( final )

**Comment by niamster** [comment]
@digitalextremist yes, I meant `0.17`.

**Comment by tarcieri** [comment]
Seems ok

**Comment by digitalextremist** [comment]
This was cut to its own branch before `0.17.5` proceeded in `master`
