### ISSUE TITLE
Workarounds for Http Timeouts?

### ISSUE THREAD

**Issue by aronchick** [celluloid/celluloid#618]
Given that timeouts are not working, and 30 seconds is too long for my current solution, is there a workaround for timing out an HTTP connection?

Alternatively, what's a way to quickly (<5 second) determine if a server is up or not?

**Comment by tarcieri** [comment]
Please have a look at `http.rb`:

https://github.com/httprb/http.rb

It has an abstract timeout system that's partly Celluloid::IO compatible, however more work is needed. It's your best bet at this point.
