### ISSUE TITLE
Prerelease versioning scheme violates semantic versioning and breaks gem dependencies

### ISSUE THREAD

**Issue by matt-altiscale** [celluloid/celluloid#620]
https://github.com/celluloid/celluloid-io/issues/144

**Comment by tarcieri** [comment]
Celluloid is using prerelease versioning conventions recommended by RubyGems:

http://guides.rubygems.org/patterns/#prerelease-gems

It seems your problem arises from the way you're doing version locking.

I'm closing this issue, but I'll leave https://github.com/celluloid/celluloid-io/issues/144 open for discussion for now.
