### ISSUE TITLE
Celluloid DNS Issue?

### ISSUE THREAD

**Issue by aronchick** [celluloid/celluloid#621]
I'm posting this here from the http.rb issues because the thought is it might be a celluloid problem. Hope you can help!

-------------

I'm doing a simple get is my code which uses the internal DNS server for my system - it looks like this ('client' is a named endpoint behind a load balancer):

```
require 'sinatra/base'
require 'sinatra-websocket'
require 'celluloid'
require 'celluloid/autostart'
require 'celluloid/io'
require 'http'
require 'byebug'

class HttpFetcher
  include Celluloid::IO

  def scan(url)
    # puts "Request -> http://#{url}"
    puts "Requesting for: #{url}"
    return HTTP.get("http://" + url).to_s
  end
end

a = HttpFetcher.new
a.scan("client/json")

a.scan("google.com")
```

When I execute this, I get "no such domain" for the first one. However, it definitely exists in my system - I can ping "client", I can curl "http://client" and when I go into Pry, and execute this, it works fine. Can you think of any reason that the way I'm executing it above would cause a problem? Is there something about the way Http.rb interacts with Celluloid that would cause a DNS issue?

* Here's example output *

```
root@dashboard-pyd9m:/home/app/dashapp# thin start -p 3000
Using rack adapter
I, [2015-05-13T13:58:30.941506 #1076]  INFO -- : Subscribing to topics.
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:3000, CTRL+C to stop
Connected to /ws.
Requesting for: client/json
DNS result has no information for client

[... repeats ...] 

Stopping ...
W, [2015-05-13T13:58:38.950896 #1076]  WARN -- : websocket closed
Client closed
D, [2015-05-13T13:58:38.951756 #1076] DEBUG -- : Terminating 58 actors...

root@dashboard-pyd9m:/home/app/dashapp# curl http://client/json
[Correct JSON]
```

**Comment by digitalextremist** [comment]
@aronchick, this is posted in `Celluloid` but it's referencing `Celluloid::IO` and possibly `Celluloid::DNS` ( except it's not using either, because it's using the local resolver and not primed to use the `Celluloid::IO` backend behavior ). There is no data to reproduce the issue, nothing in `Celluloid` involved... and @tarcieri is already answering you on httprb/http.rb#226

**Comment by tarcieri** [comment]
Per my comments on https://github.com/httprb/http.rb/issues/226 this has nothing to do with Celluloid, Celluloid::IO, etc. It's an issue with the native DNS resolution support of whatever Ruby VM you're using.
