### ISSUE TITLE
Perfomance issue with pool

### ISSUE THREAD

**Issue by ptqa** [celluloid/celluloid#622]
Hi there!

I'm trying to use celluloid with rabbitmq (bunny gem) and have a performance issue. My class is pretty basic:
```
class Generator
  include Celluloid
  attr_accessor :connect, :channel, :queue
  def initialize
    @connect = Bunny.new(user: 'admin', pass: 'admin')
    @connect.start
    @channel = @connect.create_channel
    @queue = @channel.queue('hello')
  end 

  def sendme
    @channel.default_exchange.publish('Hello World!',
                                      routing_key: @queue.name)
  end 
end
```
And when I run something like 
```
pool = [Generator.new,
Generator.new,
Generator.new,
Generator.new]

500_000.times do
  pool.sample.async.sendme
end
```

I get ~2.5k messages per sec in rabbitmq. But when I try to use library pool:
```
pool = Generator.pool(size: 4)

500_000.times do
  pool.async.sendme
end

sleep 300 
```

I get 5-10 messages per sec. So it's 200x times worse. I'm using rubinius but I also tried JRuby and it's the same. Am I missing something?

My environment:
```
rbx --version
rubinius 2.5.2 (2.1.0 7a5b05b1 2015-01-30 3.4 JI) [x86_64-linux-gnu]
celluloid (0.16.0)
```

**Comment by digitalextremist** [comment]
Let's work on this over at [`celluloid-pool`](/celluloid/celluloid-pool/issues/), the new gem which pools are provided by. Are you using `0.17.0` and the new pool code? Please move this over there and let's work on it.

**Comment by ptqa** [comment]
Ok, I'll try new gem and create new issue there if problem still appears.

**Comment by digitalextremist** [comment]
Sounds good.
