### ISSUE TITLE
Segmentation fault with 0.15.2 on MRI 2.2.2

### ISSUE THREAD

**Issue by emcgee** [celluloid/celluloid#625]
We've recently been using adhearsion 2.6.0 (https://github.com/adhearsion/adhearsion/commit/6b51039cc299c9a85064fb77bf6ef84331a4e29a, https://github.com/adhearsion/punchblock/commit/3a575bfab3bf224617c8eb6604240358a966d96e)  with MRI 2.2.2p95 and have generated a series of segfaults that seem to originate in Celluloid. 

https://gist.github.com/emcgee/9fee7ca88eea2435c388

They are somewhat sporadic and I haven't be able to fully reproduce it, but was curious if anyone had seen/heard of such a thing.

I also realize `0.15.2` is a bit behind the times but is the current version to which Adhearsion is pinned. Something that may already be fixed in `0.16.1` prerelease?

cc @benlangfeld

**Comment by tarcieri** [comment]
Celluloid is pure Ruby. By the contract the Ruby memory model is
theoretically supposed to provide, segfaults can't "originate" in Celluloid.

And confirm, the version you're using is old. Our efforts are mostly
focused on 0.17 at this point. It would be nice if Adhearsion could upgrade!

On Sunday, May 24, 2015, Evan McGee <notifications@github.com> wrote:

> We've recently been using adhearsion 2.6.0 (adhearsion/adhearsion@6b51039
> <https://github.com/adhearsion/adhearsion/commit/6b51039cc299c9a85064fb77bf6ef84331a4e29a>,
> adhearsion/punchblock@3a575bf
> <https://github.com/adhearsion/punchblock/commit/3a575bfab3bf224617c8eb6604240358a966d96e>)
> with MRI 2.2.2 and have generated a series of segfaults that seem to
> originate in Celluloid.
>
> https://gist.github.com/emcgee/9fee7ca88eea2435c388
>
> They are somewhat sporadic and I haven't be able to fully reproduce it,
> but was curious if anyone had seen/heard of such a thing.
>
> I also realize 0.15.2 is a bit behind the times but is the current
> version to which Adhearsion is pinned. Something that may already be fixed
> in 0.16.1 prerelease?
>
> cc @benlangfeld <https://github.com/benlangfeld>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/celluloid/celluloid/issues/625>.
>


-- 
Tony Arcieri

**Comment by emcgee** [comment]
Thanks @tarcieri. Tested this with `0.16.0` and the segfaults didn't reappear, so I'd consider it closed.
