### ISSUE TITLE
Tutorial linked to on wiki is semantically out-of-date and only serves to confuse, should be removed.

### ISSUE THREAD

**Issue by evanbattaglia** [celluloid/celluloid#626]
As someone trying to understand how to use Celluloid and how it is useful I went to the tutorial "Introducing Celluloid: a concurrent object framework for Ruby". There is a warning that it is syntactically out of date. Unfortunately, it appears to also be semantically out of date. It states:

`Since actors can only process one method call at a time, the call to Mapper#value will block until Mapper#run has completed, even though Mapper#run was called asynchronously.`

Oh, I get this, I think. Each actors can only run one thing at a time, that's how they ensure thread-safety. They just changed the bang syntax to async. So I make the following program:

```ruby
require 'celluloid'

class Sheen
  include Celluloid

  def initialize(name)
    @name = name
  end

  def set_status(status)
    puts "#{Time.now.to_f} start #{status}"
    sleep 1
    @status = status
    puts "#{Time.now.to_f} end #{status}"
  end

  def report
    "#{@name} is #{@status}"
  end
end

charlie = Sheen.spawn "Charlie Sheen"
charlie.async.set_status "asynchronously winning!"
charlie.async.set_status "asynchronously losing!"
puts Time.now.to_f
sleep 0.25
puts Time.now.to_f
puts charlie.report
```

To my surprise, neither of the statements above are true. Running `charlie.report` does not block, and even two async set_status methods are running at the same time. I wonder what the point of actors are then. I browse other pages on the wiki for answers but find none. I decide to give up on learning celluloid.

In this case, no documentation is probably better than wrong documentation.

**Comment by digitalextremist** [comment]
You are right that the documentation is profoundly dated. A lot more than you said. The point of actors is plain once the correct behaviors of the current code is laid out. Now that we're at a release point, the documentation is ready to not only be updated but pieced apart to various gems various functionality was moved to. Sorry for the confusion, feel free to continue this as a Google Groups discussion, and I will post a ticket addressing documentation specifically.
