### ISSUE TITLE
Celluloid::TaskFiber backtrace unavailable.

### ISSUE THREAD

**Issue by danielsalles** [celluloid/celluloid#629]
what this? I'm using only pool!

W, [2015-06-03T19:23:58.444000 #31493]  WARN -- : Terminating task: type=:finalizer, meta={:method_name=>:__shutdown__}, status=:receiving
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.

**Comment by digitalextremist** [comment]
You've run into a normal issue which isn't a bug, it has to do with how you use Celluloid. So post some code on the mailing list, and we'll help you see how to use Celluloid.

**Comment by danielsalles** [comment]
Already I asked a question there.

Thanks!
