### ISSUE TITLE
How to create multiple thread?

### ISSUE THREAD

**Issue by danielsalles** [celluloid/celluloid#630]
I'm new in this thread branch. I need accomplish several things at once. I already understand the concept of 'pool' which is for what I did not do multiple cores working on the same task. Correct?

But I am doubtful with other concepts such as: How do I create multiple threads? Example: You have a loop that reads an array and performs some things. How do I before finishing the first loop it already runs another? (I'm assuming they have no dependence)

**Comment by dodecaphonic** [comment]
I think the [Celluloid mailing list](https://groups.google.com/forum/#!forum/celluloid-ruby) is the most appropriate place for your question. Give it a go there.

**Comment by danielsalles** [comment]
Ok, sorry.

**Comment by digitalextremist** [comment]
Thank you for moving to the mailing list. We've begin discussing this there.
