### ISSUE TITLE
JRuby: Java thread count rises until JVM dies when using 0.17.0.pre15

### ISSUE THREAD

**Issue by smellsblue** [celluloid/celluloid#631]
If you run Sidekiq with Ceulluloid 0.17.0.pre15 with JRuby, your thread count will continue to increase until the JVM dies and Sidekiq with it.  I have a repo showing the problem at: https://github.com/smellsblue/threadingbug

I would be happy to contribute a fix, but I haven't delved deep enough in how Sidekiq and Celluloid work together.  Browsing around, it seems Fibers don't play well with JRuby and Celluloid... perhaps the default should be Threaded tasks when using JRuby instead of Fibered, along with a warning if you explicitly use Fibered...?  This is something I could easily contribute if Fibered tasks are just not going to be well supported on the JVM.

**Comment by digitalextremist** [comment]
@smellsblue I believe I've resolved this. Are you pulling off Github or Rubygems?

**Comment by smellsblue** [comment]
Typically Rubygems.... is there a Github branch I should try with newer code?

**Comment by digitalextremist** [comment]
If you want the newest stable code ( without this problem ) use this:

https://github.com/celluloid/celluloid/wiki/0.17.0-Prerelease

Reopen if this issue still exists. Here is what fixed your issue:

https://github.com/celluloid/celluloid/blob/0.17.0-prerelease/lib/celluloid/task/fibered.rb#L16

**Comment by smellsblue** [comment]
@digitalextremist nevermind, I tried my program against 0.17.0-prerelease branch, and it works fine! Thanks a bunch!

**Comment by digitalextremist** [comment]
No problem! It was a big problem. Sorry you had to see it, already resolved or not.

**Comment by smellsblue** [comment]
No need to apologize, I took the risk of using a prerelease gem, so I knew the potential for problems :-) just wanted to try to help resolve it. Thanks for all your work!

**Comment by digitalextremist** [comment]
By the way, you can use this to test in the future:

`gem 'cellumon', github: 'digitalextremist/cellumon', branch: 'master'`

And you can use three modes right now:

```
require 'cellumon'
monitor = Cellumon.start!
monitor.start_thread_summary!    #de Every second, thread count summary.
monitor.start_thread_report!         #de Every quarter-minute, thread report ( # running, # sleeping, etc ).
monitor.start_thread_survey!        #de Every half-minute, actual dump of threads in depth.
```

**Comment by smellsblue** [comment]
Very nice, thanks!
