### ISSUE TITLE
Select API for multiplexing futures, conditions, etc.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#632]
Similarly to how `Celluloid::IO` provides a `Reactor` for evented I/O, `Celluloid` itself needs a "Reactor" for handling collections of blocking processes such as `Future.value` and `Condition.wait` ... this allows the calling thread to continue processing when _any_ of the blocking processes are available for synchronous  operations to proceed.

Currently, all the blocking processes would have to complete, with this primitive example being the most common example:

``` ruby
futures = [
  Celluloid::Future.new { sleep 8; 3+5 },
  Celluloid::Future.new { sleep 3; 1+2 },
  Celluloid::Future.new { sleep 9; 2+7 },
  Celluloid::Future.new { sleep 5; 2+3 }
]

futures.map(&:value).map { |v| puts v }
```

In that situation, the output would be:

```
8
3
9
5
```

But with proper multiplexing, it would be:

```
3
5
8
9
```

Likely this would involve a `Multiplex` object providing muxing and demuxing. In the example, it would replace `Array` as the object the `Future` set exist in, providing an alternative to `#map`

An example of how the above would be rewritten multiplexed after the dust settles:

``` ruby
futures = Celluloid::Multiplex.new(
  Celluloid::Future.new { sleep 8; 3+5 },
  Celluloid::Future.new { sleep 3; 1+2 },
  Celluloid::Future.new { sleep 9; 2+7 },
  Celluloid::Future.new { sleep 5; 2+3 }
)

futures.map(&:value).map { |v| puts v }
```

**Comment by tarcieri** [comment]
Was literally just talking about this with a coworker today. It's a huge deficiency of Celluloid that it lacks such an API. It'd be really great to see it implemented.

**Comment by digitalextremist** [comment]
I will get it done in `0.17.5`

**Comment by digitalextremist** [comment]
In a round-about way it could either influence or be influenced by #509 ... it could end up that `Unlocker` doesn't need to ( just ) work with `Group` but with the more primitive objects like `Internals::ThreadHandle` and `Task` that wrap not just `Future` and `Condition` objects, but `Actor` objects and therefore `Call` objects.

**Comment by digitalextremist** [comment]
It seems like this is a gem.

An aside: Is `Future` a gem? @tarcieri 

From what I can see the only place where `Celluloid` depends on `Future` is with `defer` ... which it itself does not use anywhere. `Proxy::Future` and the like only get used by `Future` itself, so if all that were ripped out, `Celluloid` would be unaffected.

**Comment by tarcieri** [comment]
Rust is pretty actively splitting out parts of the core language that are better served as libraries. However, they kept `select!` as part of the core language:

https://doc.rust-lang.org/std/macro.select!.html

I'd agree with that situation, and say the same thing about futures

**Comment by digitalextremist** [comment]
Thanks for the precendent/context. Very interesting.

We'll keep `Future` *and* `Condition` in core then? In the Rust example it seems like `Future` and `Condition` would be gems and `Multiplex` would be core... if `select!` is the benchmark.

So, and aside on an aside: with Erlang/Rust/Akka being the best sources of precedent, it seems we're continuing in a vein of increasingly seeing Celluloid as more of a Ruby VM, abstracted from the "actual" Ruby Engine.

**Comment by digitalextremist** [comment]
This will likely be wise to approach laterally, by way of #669.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
