### ISSUE TITLE
SupervisionGroup not terminating

### ISSUE THREAD

**Issue by waynerobinson** [celluloid/celluloid#637]
I have a Rails app (4.2.0) with Celluloid (0.16.0) that has a small SupervisionGroup running with code similar to:

```ruby
class PublisherManager < Celluloid::SupervisionGroup
  pool Publisher, as: :publisher, size: 3
end

class Publisher
  include Celluloid
  include Celluloid::Logger

  finalizer :close_connection

  def initialize
    @client = Stomp::Client.new(BROKER_CONFIG)
  end

  def publish(queue_uri, message)
    @client.publish queue_uri, message
  end

  def close_connection
    client.try(:close)
  end
end
```

and in a config/initializers/workers.rb

```ruby
PUBLISHER_MANAGER = PublisherManager.run!
```

However, whenever Rails exits, I get the following message:

`Couldn't cleanly terminate all actors in 10 seconds!`

The actors never seem to cleanly exit. And the `#close_connection` finalizer never seems to get called.

Is there some way to safely terminate the SupervisionGroup when Rails exits?

**Comment by digitalextremist** [comment]
This is an issue we see frequently, and are resolving in the next version... but the next version is `0.17.5` and `0.17.0` is already available. Some things to try:

0. Use `0.17.0` if you can: https://github.com/celluloid/celluloid/wiki/0.17.0-Prerelease
0. Add `at_exit { Celluloid.shutdown }` to your application.
0. And/or try `at_exit { PUBLISHER_MANAGER.shutdown }`

Ideally, do all the above. And be advised, if you use `celluloid/current` ... it'll be `Celluloid::Supervision::Container` versus `Celluloid::SupervisionGroup` as if `0.17.0`

**Comment by digitalextremist** [comment]
I've retested this, and it was fixed over 90 days ago with the refactoring of `0.17.0` which took supervision out to [its own gem](https://github.com/celluloid/celluloid-supervision) and refactored it ( [along with `Pool`](https://github.com/celluloid/celluloid-pool) as well )

This has been also tested extensively using actors who have `ZMQ` sockets open, and plenty of other such connections, including `WebSocket` connections, outbound `HTTP` requests, etc. Please use `0.17.0` and make completely sure you're seeing this issue.

**Comment by waynerobinson** [comment]
For me this ended up being an interaction with Spring & Celluloid. Removing Spring solved my issue.
