### ISSUE TITLE
Adding to active Multiplexes.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#639]
Along with #632, allow adding to blocking operations that are in a waiting state.

For example, we instantiate 5 futures and wait on the resolution of the first one. Once that happens, we can add another future to the multiplex and still have 5 futures resolving.

This would allow for a sort of bounded pool-like processing pattern.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
