### ISSUE TITLE
Ship 0.17.0

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#640]
There is a `celluloid-0.17.0.rc1` gem. We've had many people testing without issue for over 30 days. Without an official gems, some people are deploying production systems with `Celluloid` pulled from the GitHub branch, for lack of a Rubygems official release. There have been around a thousand downloads of various prerelease gems, however that number is actually counted.

As soon as I'm more free, I'd like to cut and ship 0.17.0 -- even if we need to yank it for some reason. I anticipate that being toward the end of `June` ... any objections?

**Comment by tarcieri** [comment]
I'd say just ship it, then have Sidekiq users test it out. The mainstream releases of the Sidekiq gem can pin to 0.16.0 for now /cc @mperham

**Comment by digitalextremist** [comment]
Roger.

As long as `celluloid/current` is not used, Sidekiq ought to be fine, for the record.

**Comment by digitalextremist** [comment]
Roger.

As long as `celluloid/current` is not used Sidekiq ought to be fine, for the record.

**Comment by kostya** [comment]
```
/home/kostya/.rvm/gems/ruby-2.2.2/gems/celluloid-supervision-0.20.0.pre6/lib/celluloid/supervision/deprecate/supervise.rb:54:in `router': undefined method `services' for Celluloid:Module (NoMethodError)
	from /home/kostya/.rvm/gems/ruby-2.2.2/gems/celluloid-supervision-0.20.0.pre6/lib/celluloid/supervision/deprecate/supervise.rb:11:in `supervise_as'
	from /home/kostya/.rvm/gems/ruby-2.2.2/gems/celluloid-supervision-0.20.0.pre6/lib/celluloid/supervision/deprecate/supervise.rb:24:in `supervise_as'
	from /home/kostya/projects/eye/lib/eye/system_resources.rb:102:in `<class:SystemResources>'
```

from line https://github.com/kostya/eye/blob/celluloid17/lib/eye/system_resources.rb#L102

**Comment by digitalextremist** [comment]
@kostya what's the output of `gem list` for you?

**Comment by kostya** [comment]
```
celluloid (0.17.0.rc1)
celluloid-essentials (0.20.0.pre17)
celluloid-extras (0.1.4)
celluloid-fsm (0.9.0.pre13)
celluloid-io (0.16.2)
celluloid-pool (0.11.0.pre1)
celluloid-supervision (0.20.0.pre6)
```

**Comment by kostya** [comment]
fixed by `require 'celluloid/autostart'`, all specs passed.

**Comment by digitalextremist** [comment]
@kostya can you try `celluloid/current` when you get a chance, and see what breaks for you?

**Comment by kostya** [comment]
with current: `/Users/kostya/projects/eye/lib/eye/system_resources.rb:102:in `<class:SystemResources>': undefined method `supervise_as' for Eye::SystemResources::Cache:Class (NoMethodError)
`

**Comment by digitalextremist** [comment]
Change to `.supervise` and add `as:` before the symbol of its name and try again.

**Comment by kostya** [comment]
```
NameError:
       uninitialized constant Celluloid::EventedMailbox

at line: require 'celluloid/io'
```

**Comment by kostya** [comment]
fixed by `gem 'celluloid-io',  '~> 0.16.5.pre0'`, tests passed, now i run stress test.

**Comment by digitalextremist** [comment]
Very glad you thought to change the `Celluloid::IO` gem. I was unable to reply until now. Glad you're off & running. Eager to hear how it goes.

**Comment by kostya** [comment]
results of stress test, equal for each runs. 0.17 work fine, seems no leaks.

Ruby 1.9.3

|  Celluloid  | Cpu% | Rss    |
|-------------|------|--------|
| 0.15.2      |7.6   | 92288  | 
| 0.16.0      |6.5   | 91208  | 
| 0.17.0 back |7.1   | 92436  | 
| 0.17.0      |7.1   | 92088  | 

Ruby 2.2.2

|  Celluloid  | Cpu% | Rss     |
|-------------|------|---------|
| 0.15.2      |5.3   | 111668  | 
| 0.16.0      |4.2   | 121880  | 
| 0.17.0 back |4.7   | 123592  | 
| 0.17.0      |4.7   | 120452  |

**Comment by digitalextremist** [comment]
Thank you for the results! Do you have a reproducible way of producing those benchmark statistics?

**Comment by kostya** [comment]
i running multiple eyes with config examples/stress_test.eye:
```shell
eye$ rvm use 1.9.3
eye$ EYE_V=193-master bundle exec eye l examples/stress_test.eye
eye$ rvm use 2.2.2 
eye$ EYE_V=222-master bundle exec eye l examples/stress_test.eye
...
```

EYE_V should be different for each test.
to inspect daemon info `EYE_V=193-master bundle exec eye x`

**Comment by digitalextremist** [comment]
Excellent! Thank you

**Comment by digitalextremist** [comment]
Shipped the gem. Merging into master, then going to check 0.16-stable requirements another time
