### ISSUE TITLE
Quelling the ultra-loud shutdown.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#642]
There have been numerous reports of ever increasing noise at shutdown. It goes up, it goes down, it goes up again. We need to once and for all implement some kind of muzzle on the output of programs shutting down without also suppressing legitimately urgent log messages.

One option is to distinguish between `starting`, `running` and `shutdown` logging messages... but that has the obstacle of either requiring additional logger configuration ( not a real option ) or, again, suppressing legitimate messages.

**Comment by ioquatix** [comment]
You can log messages from specific components like so:

```ruby
logger = Logger.new
logger.info('starting') {'starting message'}
logger.info('stopping') {'stopping message'}
```

Just an idea?

**Comment by digitalextremist** [comment]
With the inclusion of celluloid/celluloid-essentials@b05b812cdcfedc67b62de59aec2f42f82e90756d this has settled back down.
