### ISSUE TITLE
0.17 wiki doesn't explain how to fix issues

### ISSUE THREAD

**Issue by mperham** [celluloid/celluloid#644]
The 0.17 upgrade tells me to use `celluloud/current` but doesn't actually tell me how to fix mperham/sidekiq#2420.  The deprecation page has a placeholder for help with upgrades.  If I just require 'celluloid', everything works but I get the warning.  What do I do?  See the celluloid-17 branch in sidekiq.

https://github.com/celluloid/celluloid/wiki/DEPRECATION-WARNING

**Comment by digitalextremist** [comment]
@mperham I will put up the API changes. And I might do a sweep through sidekiq to demonstrate changes, and post a PR. I will also update the Wiki, because I planned to post instructions for `0.17.5` more so than `0.17.0` because some new *additions* come in that release, not just breaking changes.

**Comment by digitalextremist** [comment]
I've added a refactoring guide, and the list of things to do is a lot smaller than I thought:

https://github.com/celluloid/celluloid/wiki/DEPRECATION-WARNING#most-common-changes

I will come back over to your thread and finish that. I got hung up with `byebug` not compiling.
