### ISSUE TITLE
Consider references and named references instead of using Registry directly

### ISSUE THREAD

**Issue by e2** [celluloid/celluloid#645]
I wanted to implement it ages, ages ago, but never got to it.

Basically, the idea is to avoid `Celluloid::Actor[:foo]` completely (due to race conditions, etc.)

Instead, one could do something like:

``` ruby
named_ref = Celluloid::NamedRef.allocate(:foo) # fails if already used
named_ref.actor = FooActor.new

ref_to_same_actor = Celluloid::NamedRef.get(:foo) # fails unless name exists
ref_to_same_actor.actor.do_something

ref_to_same_actor = Celluloid::NamedRef.wait(:foo) # waits until an actor is available under this name
ref_to_same_actor.actor.do_something

# swap out actor
ref_to_same_actor.actor = BarActor.new
named_ref.actor.do_something # all refs now refer to BarActor
```

References could solve many API problems, including those with supervisors, e.g.:

``` ruby
supervised_ref = Celluloid::SupervisedNamedRef.allocate(:foo, FooActor) # fails if already used
supervised_ref.supervise
supervised_ref.actor = some_new_actor # fails, because it's a SupervisedNamedRef
supervised_ref.actor.do_something # guarantees to contain last restarted actor
supervised_ref.do_something_useful # delegation
supervised_ref.identity # => :foo
```

Ideally, you could pass references as actors all around, and internally `Celluloid::Actor[name]` would be called every time for you. You could use those references as any normal Ruby objects, and users could subclass to customize the functionality. 

These reference class would be much easier to test - and wouldn't need "requiring behaviors" everywhere, since they introduce thread-safe composition.

Other suggestions:
`:allocate` - fails if name is used
`:new` - creates a reference to a possibly existing entry in the Registry
`:[]` - works like new
`:wait` - blocks the caller until an actor object is available under that name

This requires having access to objects by an id:
`:rename` - makes the referenced actor no longer accessible by that name (name becomes available, but all existing references still provide the same object)

**Comment by e2** [comment]
Related issues/discussions:

- https://github.com/celluloid/celluloid-supervision/issues/18
- https://github.com/celluloid/celluloid/pull/504#issuecomment-118717976

**Comment by tarcieri** [comment]
I'd suggest looking into these:

http://doc.akka.io/docs/akka/snapshot/general/addressing.html
https://github.com/uwiger/gproc

Akka specifically supports references blocking/buffering messages while a supervisor is restarting an actor. That should fix some of the raciness.

**Comment by digitalextremist** [comment]
I will look into those. The only issue with the `Celluloid[:actor]` style registry is in the resetting of the value to `nil` during a restart, so if that material covers buffering/blocking while supervisors restart actors like you say, "storing named references" is unnecessary as the registry will perform its intended function. That and celluloid/celluloid-supervision#18 cover the whole situation... with maybe some tweaks to actor proxies also.

**Comment by digitalextremist** [comment]
I'm warming up to this.

**Comment by ioquatix** [comment]
The whole registry concept is broken IMHO, the global state is a pain in the arse.

**Comment by tarcieri** [comment]
@ioquatix the entire purpose is to provide a global naming service. I think you'd be hard pressed to find an actor system that doesn't have one.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
