### ISSUE TITLE
Segfault with ruby 2.2.2 and celluloid 0.16

### ISSUE THREAD

**Issue by mtparet** [celluloid/celluloid#648]
Hey,

Since ruby 2.2.2, I'm seeing memory leaks and while I tried to debug it with gdb, I triggered a segfault which prevents me to go forward.

Could it be caused by celluloid or is it a bug in ruby (or something else) ?

The whole backtrace:
https://gist.github.com/mtparet/5217c21f0b6aebae6c27

**Comment by tarcieri** [comment]
Segfaults indicate an MRI bug. Please report it upstream.

**Comment by mtparet** [comment]
Indeed just applied latest patches with https://github.com/skaes/rvm-patchsets and it solve my problem.
Thanks
