### ISSUE TITLE
Celluloid Truck Factor

### ISSUE THREAD

**Issue by gavelino** [celluloid/celluloid#655]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Celluloid** and obtained a value of **1**.

The developer responsible for this TF is:

Tony Arcieri - author of 72% of the files 

To validate our results, we would like to ask **Celluloid** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Celluloid**?

(b) Do you agree that **Celluloid** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **Celluloid** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by digitalextremist** [comment]
a) Tony is the author. But I am active maintainer / main developer.
b) We love Tony; he has many, many pursuits. We carry load between several of us.
c) We are a well loved library with many people aware of how it works and who could step in any time.

Please take up your discussion in our google group:
https://groups.google.com/forum/#!forum/celluloid-ruby

**Comment by gavelino** [comment]
Ok. Thank you for the answer. I'll post the question on google groups.
