### ISSUE TITLE
Deprecate old API earlier than later?

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#657]
I feel like maintaining both APIs isn't helping anyone long-term. People can use `0.17.0` if they want the more stable library, i.e. no more `InternalPool`, refactored supervision and pools, cleaned out tests, etc... but if they want to update to `0.18.0` they are going to be coming after new features that they have no code for currently, like Multiplexers ( #632 ) ... Then add `1.9.3` being deprecated ( #656 ) and it seems like it's high time to be 100% new API.

**Comment by aj07** [comment]
I clearly understood the need of (#632 ) but here m not getting why 1.9.3 being depreciated  ( #656 ).
Please clarify little bit more
