### ISSUE TITLE
Omnibus Reloaded

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#658]
#### Should these be called `celluloid/core`?

I'm merging together the libraries right now, and all these are going into one:
- [ ] `Celluloid` itself.
- [ ] `Cellulid::IO`
- [ ] `Celluloid::ZMQ`
- [ ] The `celluloid-culture` gem.
  - [ ] It will no longer be a submodule.
  - [ ] It will probably be dissolved into parts of the root directory.
- [ ] The `celluloid-essentials` gem.
- [ ] The `celluloid-supervision` gem.
- [ ] The `celluloid-pool` gem.
- [ ] The `celluloid-fsm` gem.
- [ ] The `celluloid-extras` gem.
- [ ] The `celluloid-task-pooledfiber` gem.
  - [ ] _This might be a good default Task class one day._
- [ ] The `celluloid-coordinator` gem.
- [ ] The `celluloid-multiplex` gem.
- [ ] The `celluloid-logger` gem.
- [ ] The `celluloid-floss` gem.

---
#### Should these be called `celluloid/services`?

I hesitate to bring these in alongside the above. I think there ought to be an other, separate omnibus containing:
- [ ] `DCell`
- [ ] `ECell`
- [ ] `Reel`
  - [ ] `Reel::IO`
  - [ ] `Reel::DSL`
  - [ ] The `reel-rack` gem.
- [ ] `Celluloid::DNS`
- [ ] `Celluloid::SMTP`
- [ ] The `celluloid-redis` gem.
  - [ ] This might be part of `celluloid/core` but I doubt that.
- [ ] The future `celluloid-slack` gem.
- [ ] `Lattice`

---
#### Should these be `celluloid/rubysl`?

Lastly, I think these libraries are sort of the odd ones, which are more like our version of `rubysl` ... so I would include:
- [ ] The `nio4r` gem.
  - [ ] This is so crucial a gem though that I worry if it'd become more obscure in such a repository... but I supposed it'd be fine because the previous location would redirect people to here.
- [ ] The `timers` gem.
- [ ] The `timeout-extensions` gem.

---
### Issues to resolve:
- [ ] Branches... should we start purging beforehand?
  - [ ] Do we want to rename branches to `celluloid-io/branch-name`, etc?
- [ ] Releases... are they truly synchronized now, then... on a tag level?
- [ ] Issue trackers and wikis... do we keep them separate or merge?
  - [ ] Issue trackers in particular link to commit messages!
  - [ ] Should the commit messages be sanitized first?
    - [ ] Prefix all open `#XXX` messages with `celluloid/celluloid-*` programatically.
    - [ ] Otherwise we will suddenly have a clusterfuck of mislinked issues, at least in `celluloid/celluloid` ... this is part of why I advocate the `celluloid/core` approach, and just not have an Issue Tracker on it possibly.

**Comment by digitalextremist** [comment]
I created these, to think about:

- `celluloid/core`: "Foundational Celluloid libraries and gems."
- `celluloid/services` "Servers, plugins, and frameworks based on Celluloid."
- `celluloid/rubysl`: "Additions to the Ruby Standard Library."

**Comment by digitalextremist** [comment]
I have this almost ready to merge everything one after another, doing three omnirepos in a few minutes:

* [omnirepo](https://github.com/digitalextremist/omnirepo)

About to merge and push the first one to look through. Since the process is easy to redo, it doesn't matter if it's just wiped and redone.

**Comment by digitalextremist** [comment]
@tarcieri do you think it'd be alright if only master from ever repository came into the new omnirepo?

Seems like the easy flow is:

0. Clone soon to be embedded `repo`.
0. Remove submodules linkages and (empty) directories.
0. Remove all tags.
0. Move everything into a subdirectory of name `repo`.
0. Merge `repo`/master into `omnirepo`/master
0. Repeat with next embedded repository.

We could shut down push access to all the old repositories and post a note that the repository moved... and keep the branches as-is on those remnant repositories, until one day that's all out of date and unsupported/deprecated, then we remove those branches and tags on the previous repositories.

We'd have a clean set of masters for the future basically... and change logs for each file, but an incomplete connection to the past, a flattening of the past into one branch which was saved.

**Comment by digitalextremist** [comment]
The issue I'm having is sort of a catch-22 because to preserve all branches, you need a bare mirror, but with a bare mirror you can't (that I know of) move all the files into a subdirectory, because it's not a working copy, so you have no file tree available. This way, it could just be a regular clone, so there'd be a filetree to mess with and rearrange, but only one branch.

I suppose I could have the script go branch by branch and perform the rearrangement of directories... that's the only other option I see... then the branches would be preserved.

**Comment by digitalextremist** [comment]
The underlying assumption here is that we don't want to totally destroy all the issues in the tracker by suddenly having several thousand potential incorrect links to issues... so we'll keep the trackers for individual libraries, and phase out the repository itself... and have no tracker on each omnirepo.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
