### ISSUE TITLE
Configuration object, configure class method, and new starting behavior.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#660]
- [ ] Create a `Celluloid.configure { |config| }` interface to setting what would otherwise be global variables.
  - [ ] ... or allow passing in a hash to that class method.
-  [ ] Because of this convention, we only start `Actor::System` after `Celluloid.configure` runs ( in either form ) or on its first inclusion... whichever comes first.

This would still be before its first actual _use_ which probably has benefits, because until it is _included_ if it is required, it already began to use resources it may not need to.

So the `autostart` type behavior would still be there, but it would be more lazy.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
