### ISSUE TITLE
Celluloid.logger default level is DEBUG?

### ISSUE THREAD

**Issue by ioquatix** [celluloid/celluloid#667]
This seems to be overly verbose. I'd suggest at a minimum it would be INFO or WARN.

**Comment by digitalextremist** [comment]
Well, now `:debug` is by default muted..

**Comment by ioquatix** [comment]
in 0.17.1 ? I'm getting the following

```
^_^ > pry
[1] pry(main)> require 'celluloid/current'
=> true
[2] pry(main)> Celluloid::VERSION
=> "0.17.1.1"
[3] pry(main)> Celluloid.logger.level
=> 0
[4] pry(main)> Celluloid.logger.debug "Hotcakes"
D, [2015-08-19T22:14:31.952439 #64769] DEBUG -- : Hotcakes
=> true
```

**Comment by digitalextremist** [comment]
What `celluloid-essentials` version?

**Comment by ioquatix** [comment]
```
^_^ > gem list | grep celluloid
celluloid (0.17.1.1, 0.17.0, 0.16.0)
celluloid-dns (0.17.0)
celluloid-essentials (0.20.2, 0.20.0)
celluloid-extras (0.20.0)
celluloid-fsm (0.20.0)
celluloid-http (0.0.7)
celluloid-io (0.17.0, 0.16.5.pre0, 0.16.2, 0.16.1)
celluloid-pool (0.20.0)
celluloid-supervision (0.20.1, 0.20.0)
```

**Comment by TiagoCardoso1983** [comment]
Is this really relevant? You can always pass your library/app logger to Celluloid.logger and it'll all revert back to the same, it's anyways bad to have different loggers lurking around.

**Comment by ioquatix** [comment]
Is it really a good idea to output debug messages by default? If anything, having an environment variable would make more sense, i.e. by default log level is INFO (1). If CELLULOID_DEBUG is defined then make it 0 or something.

The problem with mucking around with Celluloid.logger is where to do it and what to do if multiple libraries are trying to do it?

**Comment by ioquatix** [comment]
https://github.com/celluloid/celluloid/blob/1f09c6692ef8d00972ef351d3ba66a8bf78b777c/lib/celluloid.rb#L466

So, proposing to add something like so

    Celluloid.logger = Logger.new($STDERR).tap{|logger| logger.level = Logger::INFO}

**Comment by ioquatix** [comment]
Or even:

    l = Logger.new($STDERR).tap{|logger| logger.level = Logger::INFO unless $CELLULOID_DEBUG}

**Comment by ioquatix** [comment]
@TiagoCardoso1983 this is in a library. I don't feel it's appropriate to modify logger. `Celluloid::DNS` makes use of debug messages and in normal operation generates potentially 100s or 1000s of them per second.

https://github.com/celluloid/celluloid-dns/blob/90ca3bb100acfdcfec7349e75ef60a6ae398565e/lib/celluloid/dns/server.rb#L54

The main issue for me is in specs. I could change the specs to change the log level in, say, `spec_helper.rb` but I feel for people who use `Celluloid::DNS` as a library, it's one additional thing that they'd probably want to fix before using it in production.

**Comment by ioquatix** [comment]
Okay guys I'd like to merge this. Feedback please.

**Comment by digitalextremist** [comment]
This seems fine to me
