### ISSUE TITLE
Pool fails to restart actors on Travis only? 

### ISSUE THREAD

**Issue by rmosolgo** [celluloid/celluloid#668]
Hi, 

Thanks for all your work on this gem. It's been really fun trying to learn how everything works! 

I'm trying to parallelize some tree traversal: as I go down each node, that node determines whether there are any nodes under it, and if there are, it continues downward. 

In my test suite, there are a couple tests which make sure that, if an error is raised during this process, it is either raised or returned as a string message, depending on a `debug:` switch. 

On my local environment (OSX 4-cores, I've tried Ruby 2.2.0 & 2.1.5), the test suite always passes. On Travis, the test suite fails if the error checking tests run before other tree traversal tests. Those later tests fail with `DeadActorError`, which suggests to me that the pool hasn't restarted some dead actors. 

At first, I thought the difference might be pool size, since it defaults to `Celluloid.cores`. But even setting a default pool size of 10, it continued passing locally but failing on Travis. 

Can you help me find the cause of this problem? Or why it would behave differently on Travis than locally? It seems likely that I am misusing Celluloid in some way that I don't understand! 

Here's some relevant info: 

## My code 

- [`ExecutionWorker`] (https://github.com/rmosolgo/graphql-ruby/blob/parallel-2/lib/graphql/query/parallel_execution.rb#L76-L81) performs a non-destructive proc which returns a value: 
- It's [pooled with a `Celluloid::Supervision::Container`](https://github.com/rmosolgo/graphql-ruby/blob/parallel-2/lib/graphql/query/parallel_execution.rb#L83-L85)
- The [pool is started](https://github.com/rmosolgo/graphql-ruby/blob/parallel-2/lib/graphql/query/parallel_execution.rb#L11-L14) before I do the traversal
- It's used to [find child nodes](https://github.com/rmosolgo/graphql-ruby/blob/parallel-2/lib/graphql/query/parallel_execution.rb#L60-L62) in the tree
- Later, I [recurse over those returned `Celluloid::Future`s](https://github.com/rmosolgo/graphql-ruby/blob/parallel-2/lib/graphql/query/parallel_execution.rb#L28) to get their values

## Failing Test

- During [this test](https://travis-ci.org/rmosolgo/graphql-ruby/jobs/77076327#L319-L399), a `RuntimeError` is raised during traversal, then re-raised by my code (on purpose) 
- During [this test](https://travis-ci.org/rmosolgo/graphql-ruby/jobs/77076327#L517-L542), the RuntimeError is rescued and returned as a string message 
- The [following test](https://travis-ci.org/rmosolgo/graphql-ruby/jobs/77076327#L544-L571) fails with `DeadActorError`

Is there anything else I can provide that would help find the cause of this?

**Comment by digitalextremist** [comment]
Sounds like there's a race condition in CI. I will come back to help you with this if someone else doesn't before me. I will leave this here because it's so well put together, but usually this would either be a question on the mailing list until it's determined to be a bug -- or at least posted on the gem in question; in this case [celluloid-pool](https://github.com/celluloid/celluloid-pool)

**Comment by digitalextremist** [comment]
And fyi, I magically happen to have a lab in Carlsbad, so if this gets totally out of hand for you, I have a half-room full of whiteboards. But hopefully this can be handled simply for you.

**Comment by rmosolgo** [comment]
Ohhh thanks for the tip -- actually that's quite helpful.  

For the time being, I think I can just use a fresh pool for each run. It adds some overhead of restarting & terminating, but I think it's ok for now. 

Thanks for your suggestion, and the offer to meet up! Btw if you're ever interested, we host this at our office near Palomar Airport: http://www.meetup.com/fullstacktalks/ :) 

Ok, I'll close this, feel free to reopen if you want to use it for bug tracking or something, but I'm happy!
