### ISSUE TITLE
Assess and cherry-pick Perl 6 primitives.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#669]
Assess and approximate primitives [demonstrated in Perl 6](https://www.youtube.com/watch?v=JpqnNCx7wVY) where desired, likely by creating additional gems. Cherry-pick concepts and behaviors including but not limited to:
- [ ] Lazy `.race`, and `.hybrid` methods ( and a more powerful `.map` ) by including modules.
- [ ] `React` blocks ( i.e. for "main loops" )
- [ ] `Supply` [objects, and blocks](http://doc.perl6.org/type/Supply)... and `.tap` [methods, and objects](http://doc.perl6.org/type/Tap).
- [ ] `Promise`, and `await` ( similar to `Future` )
- [ ] `whenever` with `Supply` and `React`
- [ ] `Channel` objects, for use with `Future` and `Promise`
- [ ] A `Monitor` class to `include` versus implementing an `Actor` only, rather than do intricate locking, or purely use `exclusive` behavior as an `Actor`.

These primitives would dramatically simplify `Multiplexers` ( #632, #639 ) for example. These concepts are by no means "from" `Perl 6` in every case, so where possible, also research implementations in `Erlang` and libraries like `Akka` when approximating.

**Comment by ioquatix** [comment]
Interesting. I suggested to Matz to implement channels and "go procs" as fundamental data strutures in MRI.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
