### ISSUE TITLE
Memory Leak using Celluloid::Future

### ISSUE THREAD

**Issue by hstrowd** [celluloid/celluloid#670]
I am using `Celluloid::Future` to kick off tasks and delay their execution until the result is requested. In version 0.17.0, I am finding that this is resulting in an apparent memory leak. Each call I run appears to create a new thread in the `Celluloid.actor_system.group.group` array. The `Celluloid::Group::Spawner` appears to never clean up the completed Threads that it creates.

As a work around, I am planing to instead configure my applications to use the `Celluloid::Group::Pool` group class which appears to support proper thread pooling. However in digging through this, I noticed a very aggressive warning at the top of this file (https://github.com/celluloid/celluloid/blob/master/lib/celluloid/group/pool.rb#L6), which raised a healthy level of concern for me. Don't hesitate to let me know if there is an alternative way to work around this instead. Thanks.

**Comment by kostya** [comment]
i updated eye to 0.17 (https://github.com/kostya/eye/commit/408a42ead23599dddfc7504f887dbc90c6258b47), and now also experiencing memory leak in production usage.

with https://github.com/Vasfed/heap_dump i counting leaking objects:
when process start it was 79Mb

main difference between objects:
```
Celluloid::Call::Sync: 520 
Celluloid::Future: 261
Celluloid::Future::Result: 261
Celluloid::Internals::Response::Success: 520
Celluloid::Internals::ThreadHandle: 550
```

after 8hours, 440Mb
```
Celluloid::Call::Sync: 29384
Celluloid::Future: 29178
Celluloid::Future::Result: 29178
Celluloid::Internals::Response::Success: 29384
Celluloid::Internals::ThreadHandle: 29477
```

**Comment by kostya** [comment]
to reproduce seems enough:
```ruby
require 'celluloid/current'

loop do
  f = Celluloid::Future.new { 1 }
  f.value
end
```

200Mb after 5 min.

**Comment by hstrowd** [comment]
@kostya Can you confirm which `Celluloid::Group` implementation you are using? We had to set this explicitly to `Celluloid::Group::Pool` in the following manner:

```
Celluloid.group_class = Celluloid::Group::Pool
Celluloid.init
```

**Comment by kostya** [comment]
yes this is not leaked, but why it is not the default?
```ruby
require 'celluloid/current'
Celluloid.group_class = Celluloid::Group::Pool
Celluloid.init

loop do
  f = Celluloid::Future.new { 1 }
  f.value
end
```

**Comment by marshall-lee** [comment]
@kostya ¯\\_(ツ)_/¯ https://github.com/celluloid/celluloid/blob/de28f55d6e37b6e98063aa64b82542fec8b14b29/lib/celluloid/group/pool.rb#L6

**Comment by marshall-lee** [comment]
It's not only the `Celluloid::Future` leaking. `Celluloid::Actor` leaks too :(

**Comment by marshall-lee** [comment]
@kostya could you please profile the entire Eye with my branch from #678?

**Comment by digitalextremist** [comment]
@marshall-lee yes, this is a known issue and your PR seems to be in the right track. I will review shortly.

**Comment by kostya** [comment]
@marshall-lee thanks, i applied one line `@mutex.synchronize { @group.delete Thread.current }` on production, leak fixed.
@digitalextremist can you release 0.17.1.3?

**Comment by digitalextremist** [comment]
I am working on `0.17.3` right now, but I might hold it a bit longer and release `0.17.5` with more; either way this is near @kostya.
