### ISSUE TITLE
Celluloid 0.16.1 yanked?

### ISSUE THREAD

**Issue by beneggett** [celluloid/celluloid#672]
Gem got yanked... https://rubygems.org/gems/celluloid/versions/0.16.1 

Previously working dependencies can no longer find it in rubygems. 

I still see it in the github releases: https://github.com/celluloid/celluloid/releases/tag/v0.16.1

**Comment by tarcieri** [comment]
Dup of #612

**Comment by beneggett** [comment]
Aww my bad,  didn't realize it was the same issue. Thanks for the quick reply and close
