### ISSUE TITLE
New gem dependencies not required in runtime

### ISSUE THREAD

**Issue by morgoth** [celluloid/celluloid#673]
I just updated celluloid to 0.17.0 and noticed that it now depends on gems such as `bundler`, `rspec-logsplit`.
Shouldn't they be required only for development?
Also looks like `dotenv` shouldn't be part of default dependencies.

**Comment by digitalextremist** [comment]
Duplicate of https://github.com/celluloid/culture/issues/29 -- please see that issue and continue there as needed.
