### ISSUE TITLE
This program blows up in jruby. I guess it's something in Celluloid::Conditions

### ISSUE THREAD

**Issue by pedrorolo** [celluloid/celluloid#677]
I started fiddling with celluloid and i had this trouble with this little experiment.

``` ruby
#jruby version: jruby-9.0.1.0


  require 'rubygems'
  require 'celluloid/autostart'
  require 'pry'

  module Enumerable

  class ComutativeReducerActor
    include Celluloid

    def initialize enumerable, reducer
      @enumerable = enumerable
      @n_active_actors = 0
      @available_actors = []
      @reducer = reducer
    end

    def wait_for_reduction
      @condition = Celluloid::Condition.new
      Actor.current.async.reduce
      result = @condition.wait 9000000
      result
    end

    def reduce
      if @n_active_actors > 4
        return
      end
      if @enumerable.size == 1 && @n_active_actors == 0
        @condition.signal(@enumerable.first)
        return
      elsif @enumerable.size >= 2
        pair = @enumerable[0..1]
        @enumerable = @enumerable[2..-1]
        @enumerable ||= []
        process_pair pair
        Actor.current.async.reduce
      end
    end

    def process_pair pair
      @n_active_actors = @n_active_actors + 1
      reducer = \
      if @available_actors.empty?
        SingleReducer.new pair: pair, reducer: @reducer, parent: Actor.current
      else
        a = @available_actors.first
        @available_actors = @available_actors[1..-1]
        @available_actors ||= []
        a.tap do |a|
          a.pair = pair
          a.parent = Actor.current
        end
      end
      reducer.async.reduce
    end

    def add_new_value value, actor
      @enumerable << value
      if (@enumerable.size / 4) > @available_actors.size
        @available_actors << actor
      else
        actor.terminate
      end
      @n_active_actors = @n_active_actors - 1
      Actor.current.async.reduce
    end
  end

  class SingleReducer
    include Celluloid
    attr_accessor :pair
    attr_accessor :parent

    def initialize pair: nil, reducer: nil, parent: nil
      @pair = pair
      @reducer = reducer
      @parent = parent
    end

    def reduce
      result = nil
      if @pair.size == 1
        result = @pair.first
      else
        result = @reducer.call @pair.first, @pair.last
      end
      @parent.async.add_new_value(result, Actor.current)
    end
  end

  def comutative_reduce &reducer
    reducer = ComutativeReducerActor.new self, reducer
    val = reducer.wait_for_reduction
    reducer.terminate
    val
  end
  end


  puts ([1,2,4,5,6]*100).comutative_reduce{|a,b|
    a * b
  }
```

Error:

E, [2015-09-19T21:20:12.406000 #46502] ERROR -- : Actor crashed!
ArgumentError: wrong number of arguments (1 for 0)
    /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/system_events.rb:6:in `handle_system_event'
    /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/actor.rb:123:in`block in initialize'
    org/jruby/RubyProc.java:308:in `call'
    /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-essentials-0.20.2.1/lib/celluloid/internals/handlers.rb:38:in`call'
    /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-essentials-0.20.2.1/lib/celluloid/internals/handlers.rb:20:in `handle_message'
    /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/actor.rb:283:in`handle_message'
    /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/actor.rb:156:in `block in run'
    /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/timers-4.1.1/lib/timers/group.rb:69:in`wait'
    /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/actor.rb:152:in `run'
    /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/actor.rb:131:in`block in start'
    /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-essentials-0.20.2.1/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
    /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/actor/system.rb:78:in`block in get_thread'
    org/jruby/RubyProc.java:308:in `call'
    /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/group/spawner.rb:53:in`block in instantiate'
Celluloid::TaskTerminated: task was terminated
              suspend at /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/task.rb:75
              suspend at /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/task.rb:11
              suspend at /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid.rb:139
                 wait at /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/condition.rb:58
   wait_for_reduction at comutative_reduce_actors.rb:20
          public_send at org/jruby/RubyKernel.java:1823
             dispatch at /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/calls.rb:28
             dispatch at /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/call/sync.rb:16
    block in dispatch at /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/cell.rb:50
        block in task at /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/cell.rb:76
        block in task at /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/actor.rb:339
  block in initialize at /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/task.rb:44
      block in create at /Users/pedro/.rvm/gems/jruby-9.0.1.0/gems/celluloid-0.17.1.2/lib/celluloid/task/fibered.rb:14

**Comment by olleolleolle** [comment]
Hello, I made very small changes to this program, and it runs on current JRuby 9.1.7.0.

Here is the program I ran: https://gist.github.com/olleolleolle/ddd12626d8651b256531b97880334620

Changes made:

- Removed the `celluloid/autostart ` which is represented by the automatically-enabled BACKPORTED mode
- Rubocop auto-correct
- assigned the `result` variable, and then `puts`ing it

Output now:

```
I, [2017-02-25T19:53:30.368000 #4979]  INFO -- : Celluloid 0.17.3 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
10498425511251795460213018874278345341399548969203826401953216956503410439129480752471812805408412727108818480063503708244128179108456693760000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```
