### ISSUE TITLE
Performance oriented refactoring.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#683]
At the prompting of @TiagoCardoso1983's benchmarking, posted on the mailing list:

https://groups.google.com/forum/#!topic/celluloid-ruby/5ybUSbNrYJw

And in consideration of mperham/sidekiq#2583

... instead of moving on to new features and gem decoupling in a `0.18.0` release: an interim `0.17.5` release will include a performance audit and refactoring, across the board.

Before and after benchmarks will be posted, and the tests used to get those benchmarks ought to be monitored closely in controlled environments ( i.e. not high-traffic servers like CI )

**Comment by digitalextremist** [comment]
Here you go @aayushranaut -- per our brief discussion.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
