### ISSUE TITLE
Request: prefix all standard Actor names in order to avoid conflicts.

### ISSUE THREAD

**Issue by clonezone** [celluloid/celluloid#684]
For example, instead of the Celluloid::Notifications::Fanout being "notifications_fanout", make it "celluloid_notifications_fanout".

I'm just worried about my code accidentally conflicting with standard Actor names.

**Comment by digitalextremist** [comment]
What about *optional* prefixing of system instantiated actors, using a constant that if unset keeps the same behavior as now?

**Comment by clonezone** [comment]
How much non-celluloid code is directly using those names now? The names are nicely hidden behind methods already, e.g. the C::N::Fanout instance is accessed via C::N.notifier().

**Comment by clonezone** [comment]
BTW, I'm about to name an Actor "notifications_manager" because that's what makes sense for my system. Do I need to worry about Celluloid grabbing that?

**Comment by clonezone** [comment]
I would worry about the naïve Celluloid user that doesn't realize that they can't use "incident_reporter" as an Actor name.

**Comment by digitalextremist** [comment]
This isn't that huge of an issue but I need to bump this to the next version. I am going to talk to some of the other core contributors to make sure we don't have anyone directly depending on those symbols.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
