### ISSUE TITLE
cannot load such file -- dotenv and unable to boot Celluloid during tests

### ISSUE THREAD

**Issue by Tonkpils** [celluloid/celluloid#685]
In previous versions of Celluloid (0.16.2 as far back as I've seen it work), requiring `celluloid/rspec` worked in the following code for running `rspec spec` https://github.com/Tonkpils/celluloid-eventsource/blob/master/spec/spec_helper.rb#L5 

With the latest release of Celluloid (0.17.2), it seems that changes were made to the `celluloid/rspec` file which caused it to require `dotenv` which is not part of the gems brought along during bundle install.

That's fine since I could not find documentation which stated that `celluloid/rspec` should be required for tests. I went on to require `celluloid/test` and ran into all my specs failing with the error `Celluloid is not yet started; use Celluloid.boot`

I tried adding a `before` hook on my spec_helper to run the commands suggested by https://github.com/celluloid/celluloid/wiki/Gotchas#testing with no luck. Is there new documentation which points to how to test with Celluloid?

**Comment by Tonkpils** [comment]
Hmm, seems that requiring `celluloid/test` and adding an `around` hook with 

```
config.around(:each) do |ex|
  Celluloid.boot
  ex.run
  Celluloid.shutdown
```

seemed to do the trick.

**Comment by rally25rs** [comment]
Ran into the same issues. It seems like the [Testing wiki page](https://github.com/celluloid/celluloid/wiki/Testing) is out of date, and there are surprisingly few google results for testing celluloid 😞 

Your `around` hook didn't work for me, but it seems that you just have to have called `Celluloid.boot` _before_ any `require 'celluloid'` calls. So if you do the "standard ruby" thing and requiring files at the top;

_some_job.rb_
```ruby
require 'celluloid/current'

class SomeJob
  include Celluloid

  def run
  end
end
```

_something.rb_
```ruby
require 'some_job'

SomeJob.run
```

_something_spec.rb_
```ruby
require 'celluloid/test'
require 'something' # <-- exception here because not booted yet

describe 'something' do
  around(:each) do |ex|
    Celluloid.boot
    ex.run
    Celluloid.shutdown
  end
end
```

It ends up not working.

I had to boot celluloid momentarily just so it could be `require`d

```ruby
require 'celluloid/test'
Celluloid.boot # temporarily boot just so celluloid can be required
require 'something' # eventually requires 'celluloid/current' successfully
Celluloid.shutdown # the around hook will re-boot celluloid when needed
```

That gets my test running anyway... I run into other issues where I can't mock anything on the celluloid class under test, and anything that uses the DB seems to completely not work, only inside rspec but works when run "for real", but that is another fight....
