### ISSUE TITLE
Segmentation Fault 

### ISSUE THREAD

**Issue by tpal-systango** [celluloid/celluloid#687]
I am facing the problem in Development environment  . I think It may be due to the Sucker Punch Gem but I can't recognized why this error I am getting . It stopped the rails server.

/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:10: [BUG] Segmentation fault
ruby 1.9.2p320 (2012-04-20 revision 35421) [x86_64-linux]

-- control frame ----------
c:0024 p:0066 s:0089 b:0089 l:001d08 d:001d08 METHOD /home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:10
c:0023 p:---- s:0084 b:0084 l:000083 d:000083 CFUNC  :resume
c:0022 p:0015 s:0080 b:0080 l:000079 d:000079 METHOD /home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:25
c:0021 p:0047 s:0075 b:0075 l:000074 d:000074 METHOD /home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:96
c:0020 p:0026 s:0071 b:0071 l:000e08 d:000e08 METHOD /home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/actor.rb:353
c:0019 p:0058 s:0066 b:0066 l:000d28 d:000d28 METHOD /home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/cell.rb:67
c:0018 p:0108 s:0059 b:0059 l:001c68 d:001c68 METHOD /home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/cell.rb:59
c:0017 p:0012 s:0054 b:0054 l:002178 d:000053 BLOCK  /home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/cell.rb:34
c:0016 p:---- s:0051 b:0051 l:000050 d:000050 FINISH
c:0015 p:---- s:0049 b:0049 l:000048 d:000048 CFUNC  :call
c:0014 p:0015 s:0045 b:0045 l:000044 d:000044 METHOD /home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:38
c:0013 p:0032 s:0041 b:0041 l:000040 d:000040 METHOD /home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:19
c:0012 p:0015 s:0036 b:0036 l:000035 d:000035 METHOD /home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/actor.rb:280
c:0011 p:0053 s:0032 b:0032 l:001370 d:000031 BLOCK  /home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/actor.rb:154
c:0010 p:0025 s:0028 b:0028 l:000027 d:000027 METHOD /home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/timers-4.0.1/lib/timers/group.rb:52
c:0009 p:0023 s:0023 b:0023 l:001370 d:001370 METHOD /home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/actor.rb:150
c:0008 p:0019 s:0019 b:0019 l:0005a8 d:000018 BLOCK  /home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130
c:0007 p:0032 s:0017 b:0017 l:0004d8 d:000016 BLOCK  /home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13
c:0006 p:0030 s:0015 b:0015 l:0000d8 d:000014 BLOCK  /home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32
c:0005 p:---- s:0013 b:0013 l:000012 d:000012 FINISH
c:0004 p:---- s:0011 b:0011 l:000010 d:000010 CFUNC  :call
c:0003 p:0021 s:0008 b:0008 l:001718 d:000007 BLOCK  /home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:---- s:0002 b:0002 l:000001 d:000001 TOP   
---------------------------
-- Ruby level backtrace information ----------------------------------------
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/actor.rb:150:in `run'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/timers-4.0.1/lib/timers/group.rb:52:in `wait'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/actor.rb:154:in `block in run'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/actor.rb:280:in `handle_message'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:19:in `handle_message'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:38:in `call'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:38:in `call'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/cell.rb:34:in `block in initialize'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/cell.rb:59:in `invoke'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/cell.rb:67:in `task'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/actor.rb:353:in `task'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:96:in `resume'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:25:in `deliver'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:25:in `resume'
/home/tpal/.rvm/gems/ruby-1.9.2-p320@iqglobal_new/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:10:in `create'

-- C level backtrace information -------------------------------------------
/home/tpal/.rvm/rubies/ruby-1.9.2-p320/lib/libruby.so.1.9(rb_vm_bugreport+0x5e) [0x7f240084baee]
/home/tpal/.rvm/rubies/ruby-1.9.2-p320/lib/libruby.so.1.9(+0x659fe) [0x7f240071b9fe]
/home/tpal/.rvm/rubies/ruby-1.9.2-p320/lib/libruby.so.1.9(rb_bug+0xa5) [0x7f240071c615]
/home/tpal/.rvm/rubies/ruby-1.9.2-p320/lib/libruby.so.1.9(+0x122004) [0x7f24007d8004]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40) [0x7f2400327d40]
/home/tpal/.rvm/rubies/ruby-1.9.2-p320/lib/libruby.so.1.9(+0x18a527) [0x7f2400840527]
/home/tpal/.rvm/rubies/ruby-1.9.2-p320/lib/libruby.so.1.9(rb_vm_invoke_proc+0xe1) [0x7f2400840731]
/home/tpal/.rvm/rubies/ruby-1.9.2-p320/lib/libruby.so.1.9(+0x19cc0b) [0x7f2400852c0b]
/home/tpal/.rvm/rubies/ruby-1.9.2-p320/lib/libruby.so.1.9(+0x19ccfa) [0x7f2400852cfa]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8182) [0x7f24000db182]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f24003eb47d]

**Comment by tarcieri** [comment]
Segfaults indicate a bug in the Ruby interpreter or a native extension and cannot be caused by Celluloid, a pure-Ruby library.

**Comment by pboling** [comment]
The first thing to try is rebuild your Ruby install, and re-bundle install your gems.  If you recently upgraded, say, Mac OS X, your Rubies likely must be reinstalled.
