### ISSUE TITLE
Error bundle installing when using github repo

### ISSUE THREAD

**Issue by krisleech** [celluloid/celluloid#690]
Might be related to [this issue](https://github.com/celluloid/celluloid/issues/671), when I try to use the git repo version of celluloid I get an error when bundle installing.

```ruby
gem 'celluloid', github: 'celluloid/celluloid'
```

```
$ bundle install
Updating git://github.com/celluloid/celluloid.git
There was a LoadError while loading celluloid.gemspec: no such file to load --
/celluloid-7e51d7e8881e/culture/sync 
from 
/celluloid-7e51d7e8881e/celluloid.gemspec:3:in `<eval>'

Does it try to require a relative path? That's been removed in Ruby 1.9.
```

I'm using jruby 9.0.3.0 (2.2.2) 2015-10-21 633c9aa Java HotSpot(TM) 64-Bit Server VM 25.40-b25 on 1.8.0_40-b25 +jit [darwin-x86_64]

Is this known?

**Comment by aayushranaut** [comment]
culture is a submodule in git. You need to recursively install all the submodules when cloning the repo.
You have two options.
1. If you haven't cloned the repo yet. Run the following command.
'git clone --recursive https://github.com/aayushranaut/celluloid'

2. If you have already cloned the repo. Run the following command.
'git submodule update --init --recursive'

**Comment by digitalextremist** [comment]
Thank you @aayushranaut, yes. Sorry @krisleech. This will be wrapped up before `GSoC` formally starts this year.

**Comment by digitalextremist** [comment]
Closing in favor of #706 with @aayushranaut's advise being correct in the meantime.

@aayushranaut would you mind including your answer in the `README.md` where it fits well, and sending a PR?

**Comment by aayushranaut** [comment]
```ruby
gem 'celluloid', github: 'celluloid', submodules: true
```

Submodules is key here.

**Source:** https://github.com/celluloid/celluloid/blob/master/CONTRIBUTING.md

@digitalextremist I think I could move something like this to the main readme as a set of instructions for alternative installation via github. What do you think?

**Comment by digitalextremist** [comment]
Yes, please post a PR & will merge!
