### ISSUE TITLE
JRuby block handling messing celluloid event handling

### ISSUE THREAD

**Issue by TiagoCardoso1983** [celluloid/celluloid#694]
Refering to this line:

https://github.com/celluloid/celluloid/blob/master/lib/celluloid/system_events.rb#L113

This apparently fails in JRuby. I switched this locally to:

```ruby
handler do |e|
  e.call
end
#handler(&:call)
```

and it worked again.

My guess is, this is either a JRuby bug or undefined behaviour. I first thought it was this:

```ruby
 p = proc { puts "balls" }
 p.call #=> "balls"
p.call(1) #=> "balls"

 def test ; puts "balls" ; end 
method(:test).to_proc.call #=> "balls"
method(:test).to_proc.call 1 #=> ArgumentError
```
but CRuby 2.0 behaves the same way. Then I thought it was because of the [define_method meta-definition](https://github.com/celluloid/celluloid/blob/master/lib/celluloid/system_events.rb#L31) that could be different, but I somehow couldn't reproduce the error. This seems, however, to work flawlessly in CRuby but fail all the time in JRuby (at least since 9.0.0.0, according to #677 ). 

@digitalextremist  can you give your 2 cents? (this block seems to come from you). @headius what do you think, is jruby to blame for this? If the problem is indeed jruby, can't we just replace that &:call part with a proper block and event method call, as this is supported? I can submit a pull request as soon as we figure out where should this be fixed.

**Comment by digitalextremist** [comment]
Thank you for the detailed information about this nuanced variation @TiagoCardoso1983... 

Curious to hear from @headius on why the `&` invocation style does not work as expected.

I'd merge a PR with your version, citing the reference below as already using that style ( fortuitously, evidently ):

https://github.com/celluloid/celluloid/blob/master/lib/celluloid/system_events.rb#L51
