### ISSUE TITLE
"Couldn't cleanly terminate all actors in 10 seconds!" with Spring 1.6.0 and Rails 5.0.0.beta1

### ISSUE THREAD

**Issue by dhh** [celluloid/celluloid#696]
Rails 5.0.0.beta1 encourages you to mount the Celluloid-powered `ActionCable.server` in-process by changing the routes.rb file to uncomment `mount ActionCable.server => '/cable'`. When you do that, generator commands (that presumably do a fork somewhere) start hanging with the following error message: `E, [2015-12-20T08:09:19.218168 #5720] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!`.

You can provoke this with:

```
rails new terminator
cd terminator
./bin/rails generate scaffold post title:string
```

If you remove the Spring loader from bin/rails, there is no problem.

**Comment by dhh** [comment]
//cc @tarcieri @grosser

**Comment by tarcieri** [comment]
There was previously a fix for this for 0.16.x (see #612). However, between 0.16 and 0.17 the default thread spawning strategy changed (thread pool -> spawn-on-demand), and the fix for this regressed.

**Comment by mike-ball** [comment]
Any plans to fix this in a new update to 0.17?

**Comment by ivanilves** [comment]
Yes, fix it please :pray:

**Comment by simonc** [comment]
Is there any workaroud in the meantime? It's also happening with a Rails 4 app when Sidekiq is used. Every command takes ages to stop even a simple `rake db:migrate` takes forever :'(

**Comment by digitalextremist** [comment]
@simonc are you using Rubinius or MRI?

**Comment by simonc** [comment]
@digitalextremist MRI v2.3.1.

**Comment by digitalextremist** [comment]
Waiting on CI then good to go.

**Comment by digitalextremist** [comment]
( `listen` and therefore `guard` is causing the build to error, but feel free to use `master` as-is in the meantime; it has the fix )

**Comment by simonc** [comment]
@digitalextremist actually I cannot use `master` right now, when adding this to my Gemfile
```ruby
gem 'celluloid', github: 'celluloid/celluloid'
```
I get the following error when calling `bundle install`
```
Fetching git://github.com/celluloid/celluloid.git
There was a LoadError while loading celluloid.gemspec:
cannot load such file -- /Users/xxx/.gem/ruby/2.3.1/bundler/gems/celluloid-8d8f1d460d79/culture/sync from
  /Users/xxx/.gem/ruby/2.3.1/bundler/gems/celluloid-8d8f1d460d79/celluloid.gemspec:3:in `<main>'

Does it try to require a relative path? That's been removed in Ruby 1.9.
```

**Comment by sfroehler** [comment]
@simonc I had the same issue. The culture folder is a git submodule so you have to tell bundler to load submodules with ```submodules: true```:

```ruby
gem "celluloid", git: "https://github.com/celluloid/celluloid", submodules: true
```

**Comment by digitalextremist** [comment]
Needs `submodules: true` also.

**Comment by simonc** [comment]
@sfroehler Much better :grim: Thanks!

**Comment by digitalextremist** [comment]
#706 will solve subsequent issue, 8d8f1d4 solved original issue; see https://github.com/celluloid/celluloid/issues/696#issuecomment-221195865 for temporary fix in the meantime until the next point release is cut. The CI/build errors are removed finally.

**Comment by wdrury** [comment]
This continues to be a problem with Celluloid 0.17.3 and Spring 2.0.2.  New release any time soon?

**Comment by jhubert** [comment]
@wdrury Have you tried using the 0.18.0.pre release of Celluloid? That fixed the issue for us.
