### ISSUE TITLE
Use celluloid-culture as a gem

### ISSUE THREAD

**Issue by balasankarc** [celluloid/celluloid#706]
Hi,
I am part of the team that maintains the package of celluloid gem in Debian. Right now, all celluloid-* gems use 'culture/sync' in gemspec and many other files using a relative path (which,also uses a git submodule). It is extremely difficult to handle submodules when it comes to distribution of a software.

I saw celluloid-culture is available as a gem. So, can you switch over to using it as a gem (using `require 'celluloid/culture`) so that it makes the life of package managers easy?

**Comment by digitalextremist** [comment]
Hello @balasankarc, we are in the process of removing `culture` as a submodule, and removing all the relative interdependencies you're noticing. Sorry for the trouble //

**Comment by anthraxx** [comment]
Hi, just wanted to mention: thanks a lot. Just came around as I wanted to also ask for improvement as it really hurts packaging (I'm from Arch Linux).
However the current gem just seems to be a placeholder, or am I wrong? The important sync.rb is not inside it when i create the gem from the gemspec source so its about more then just use that require

**Comment by digitalextremist** [comment]
Yes, in `0.17.5` / `0.18.0` ( the release after the one going out shortly, `0.17.4` ) this will be removed. Feel free to reopen this issue if it's still a problem after the submodule is removed.
