### ISSUE TITLE
Fiber.yield should not be used to exit fiber

### ISSUE THREAD

**Issue by headius** [celluloid/celluloid#716]
I found this code in `fibered.rb` while investigating a JRuby+Celluloid issue:
```ruby
module Celluloid
  class Task
    # Tasks with a Fiber backend
    class Fibered < Task
      class StackError < Celluloid::Error; end
      def create
        queue = Thread.current[:celluloid_queue]
        actor_system = Thread.current[:celluloid_actor_system]
        @fiber = Fiber.new do
          # FIXME: cannot use the writer as specs run inside normal Threads
          Thread.current[:celluloid_role] = :actor
          Thread.current[:celluloid_queue] = queue
          Thread.current[:celluloid_actor_system] = actor_system
          yield
          # TODO: Determine why infinite thread leakage happens under jRuby, if `Fiber.yield` is used:
          Fiber.yield unless RUBY_PLATFORM == "java"
        end
      end
...
```

Note the TODO here.

If this `Fiber.yield` is intended to be the last thing the fiber does, then it would be better to just let it fall off the bottom of the fiber.

In MRI, when you do a Fiber.yield, the calling fiber gets swapped out and might GC if its Fiber object becomes dereferenced. In JRuby, where fibers are each implemented by a thread, we need finalization to actually kill the Fiber's thread, and that may take a while if there's no other GC pressure. I suspect this `Fiber.yield` could just be omitted for all Rubies, since the last resume for the fiber is supposed to return the last value of the block.

**Comment by digitalextremist** [comment]
@headius aren't we falling off there by the `unless` portion?

**Comment by headius** [comment]
Sorry, yes...I just mean you can remove the whole line, and wanted to explain why the original code leaks threads on JRuby.

**Comment by digitalextremist** [comment]
I think this is @niamster's wheel house, per an issue we're still on, #463 I believe.

**Comment by tarcieri** [comment]
I have no idea where that `Fiber.yield` came from or what the intention of having it there is.

I haven't taken the time to bisect, but it looks like it got added some time between 0.16 and 0.17:

https://github.com/celluloid/celluloid/blob/0-16-stable/lib/celluloid/tasks/task_fiber.rb

I would suggest removing it unless there's a good reason for having it there.

**Comment by headius** [comment]
If I didn't make it clear, this last `yield` actually makes the fiber stick around *longer* on most implementations, since it's still waiting for one more resume.

**Comment by digitalextremist** [comment]
Thanks again for bringing this up @headius. I've since gone through and audited many areas and applied the change you said.
