### ISSUE TITLE
ThreadError: deadlock; recursive locking

### ISSUE THREAD

**Issue by tmornini** [celluloid/celluloid#719]
Hey guys. We're experiencing:

```
ThreadError: deadlock; recursive locking 
```

on Ruby 2.2.5 and 2.3.1 and these versions of Celluloid:

```
celluloid-essentials 0.20.5
celluloid-extras 0.20.5
celluloid-fsm 0.20.5
celluloid-pool 0.20.5
celluloid-supervision 0.20.5
celluloid 0.17.3
```

It _may_ be related to [this Ruby bug](https://bugs.ruby-lang.org/issues/11953). Note that other participants on that ticket indicate that 1.9.3 tip (which we have not tested against) and 2.2.4 do not exhibit this behavior.

This happens very reliably in a section of code where we intentionally let an exception bubble up to terminate the actor -- which is then restarted by a Supervisor.

**Comment by digitalextremist** [comment]
Will keep an eye out for this @tmornini -- out of curiosity, does your design specifically call for `MRI` or could `Rubinius` or `jRuby` be used?

**Comment by tmornini** [comment]
Unfortunately, we do not feel confident that the majority of our code will run successfully on either.

**Comment by digitalextremist** [comment]
@tmornini does the repro listed in the linked bug produce the `ThreadError` for you?

**Comment by digitalextremist** [comment]
I've looked at the code referenced, and only one of the two produces the exception under `2.2.5` -- the one that does, the second of the two, fails in `Singleton`

Going to need a reproduction and/or more of a description of the operations involved @tmornini?

**Comment by marcandre** [comment]
Is this related to the change in the `prime` library? Could we have the full stacktrace?

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
