### ISSUE TITLE
Optimize Fibers for MRI 2.3.1 & Rubinius 3.40+

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#724]
As pointed out by @brixen, during discussions while refactoring `Rubinius` to implement `Fiber` using `pthreads`... the way we currently use `Thread` locals is not compatible with `2.3.1` -- when asked "how has `Celluloid` historically used `Fiber` and what experiences have we had" -- it became clear this is an area where we're using out-dated semantics which are implemented differently from engine to engine. Back in `1.9.3` we used `Thread#[]` as if it were an accessor to thread locals, but it is now in fact the accessor of `Fiber` locals.
## Contrast the terminology:
- `2.3.1`: http://ruby-doc.org/core-2.3.1/Thread.html#method-i-5B-5D
- `1.9.3`: http://ruby-doc.org/core-1.9.3/Thread.html#method-i-5B-5D
## `tl;dr` version...
- What we treat as `Thread#[]` is _actually_ `Thread#thread_variable_get`
- What we treat as `Thread#[]=` is _actually_ `Thread#thread_variable_set`

The immediate performance ramifications of this is the ability to avoid copying "thread locals" into each new fiber spawned, which can be going on many thousands of times per second. At least in the case of `Rubinius 3.40` there is a high-performance workaround possible; and we'll need to see how `jRuby` behaves here too...
- If `Thread.method_defined? :thread_variable_get` then it is possible to alias `#[]` to `#thread_variable_get` with the potential side-effect of disrupting down-stream developers; otherwise we can refactor to make use of the new API which will likely remove the need for us to copy references into the new `Fiber` instances.

---

There is a near insane-hope side to this: perhaps the way we use `Fiber` is actually out of step with the language spec now, and _that_ could contribute to #463?

**Comment by digitalextremist** [comment]
@aayushranaut watch this issue closely, this is one of the most performance-intensive aspects of `Celluloid`

**Comment by chuckremes** [comment]
I just checked the history at ruby-doc.org and it shows that `Thread#thread_variable_get` and `set` were introduced as of 2.0.0. The semantics changed with the 2.x series which pretty much everyone should be using by now. Can we just deprecate 1.9 and say next release is MRI 2.x and later?

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
