### ISSUE TITLE
0.17.4/0.18.0 due out when?

### ISSUE THREAD

**Issue by HerbCSO** [celluloid/celluloid#728]
I would love to be able to take advantage of the `fork` fix (#696) without having to use the `master` release. Any chance there could be a 0.17.4 release sometime soon?

**Comment by digitalextremist** [comment]
This will be within the next few weeks at the most. We are in the middle of Google summer of code and doing repository maintenance. Thank you for your patience

**Comment by HerbCSO** [comment]
Sweet, thanks for the info, that's perfect!

**Comment by digitalextremist** [comment]
Strangely, out of everywhere in the world I could be -- I believe that right about when you initiated this ticket, I had just crossed from `DC` into `Arlington` in my car, at basically the mid-point in a 7,000-mile trip around the US. That's crazy.

**Comment by HerbCSO** [comment]
@digitalextremist any news on the new release? Anything I could jump in and help on to help push it over the edge (frankly I don't know that I can help much, but I'm willing to roll up my sleeves on something small to get my feet wet ;] )?

**Comment by digitalextremist** [comment]
@HerbCSO `GSoC` just finished over the last few days. Now, after both years we've done, we have @dilumn and @prathmeshranaut possibly willing to jump in here to help ( there are others but I think these two guys might be the most prepared for this ticket ) so I invited them to jump in here. If they/you are not able to jump in and/or I can't answer whatever they/you need to get through this, I will be finally back to this in the next 7-10 days for a bit. Thanks very much for your patience!

**Comment by HerbCSO** [comment]
Great, thanks so much!

**Comment by dilumn** [comment]
@HerbCSO Always welcome to contribute to `celluloid`. [Here](https://github.com/celluloid/celluloid/labels/easyish) are the issues labelled `easyish`. You can start things from there & reading the [wiki](https://github.com/celluloid/celluloid/wiki) will make you more comfortable

**Comment by digitalextremist** [comment]
@dilumn I am guessing @HerbCSO is in a situation where he needs `Celluloid` to release a new version, so is offering to help just in this instance. I am trying to avoid that for him though, if you could help get this release out that would be great since you are more prepared. I am on `Slack` as usual

**Comment by HerbCSO** [comment]
@digitalextremist that is correct.

I really don't wanna be a pest, but I'm gonna pester you anyway... ;] Any news on the release date for the next version? I'm really not trying to be pushy here, just wanna see what kind of timeframe I should expect to be working with.

Thanks!

**Comment by HerbCSO** [comment]
I _really_ hate to be such a pest - but is there any chance of a new release on the horizon here?

**Comment by tarcieri** [comment]
@digitalextremist I think we should plan on releasing master as 0.18.0 soon

**Comment by bjreath** [comment]
@digitalextremist Anything a community member can be doing to help with cutting a release?

**Comment by tarcieri** [comment]
@bjreath I'll look at pushing out a set of `0.18.0.pre` releases this weekend. You can help by testing them!

**Comment by bjreath** [comment]
@tarcieri Sounds good. Thanks!

**Comment by fgrehm** [comment]
@tarcieri I hate to be the one to ask this question but do we have any ETA on this? Tks a lot in advance 🍻

**Comment by ccoenen** [comment]
The .pre has been delivered as promised. Did you try it? It's been out there for half a year without major complaints - chances are, it's stable.

**Comment by fgrehm** [comment]
@ccoenen oh sorry, I'm giving that a shot today. we had an issue in the past with an upgrade but I didn't realize we haven't given 0.18.0.pre a shot 🤦‍♂️ I'll report back in case we find any issues! 🍻

**Comment by zsiddique** [comment]
Can we reopen this issue? https://github.com/celluloid/celluloid/issues/762

**Comment by jhubert** [comment]
Just confirming for others that we're using 0.18.0.pre successfully in production on a high traffic app for both launchdarkly and actioncable.

**Comment by tarcieri** [comment]
I would like to coordinate a 0.18 release but am short on time.

If anyone would like to help with the busywork of doing a release, I would be happy to help advise what needs to be done.

Unfortunately it's been a long time since the last release (almost 2 years) which makes things that much harder. I don't want to do a release after so long without good documentation of what has changed, which is quite a bit.
