### ISSUE TITLE
Seems that deprecation is shown up when it should not

### ISSUE THREAD

**Issue by aliaksandrb** [celluloid/celluloid#732]
Hi There!

Using the `Celluloid 0.17.3` and get the "INFO -- : Celluloid 0.17.3 is running in BACKPORTED mode. [ http://git.io/vJf3J ]" message when run it.
According to link above I should switch to `require 'celluloid/current'` over `require 'celluloid'` / `require 'celluloid/autostart'` which I definitely did.
But that message still pop-up.

When I've checked where it comes from I've found interesting stuff in the `celluloid/lib/celluloid.rb` file, specially:

``` ruby
$CELLULOID_BACKPORTED = false if defined?(CELLULOID_FUTURE) && CELLULOID_FUTURE
$CELLULOID_BACKPORTED = (ENV["CELLULOID_BACKPORTED"] != "false") unless defined?($CELLULOID_BACKPORTED)
Celluloid::Notices.backported if $CELLULOID_BACKPORTED
```

Pretty straightforward but: 
- Grepping on `CELLULOID_FUTURE` - shows that it never get defined in celluloid repo, so first assign not occurs and we go to next line
- ENV["CELLULOID_BACKPORTED"] != "false" - unfortunately by default I have no `CELLULOID_BACKPORTED` env variable assigned, which means that it will be nil which is != 'false', that leads to $CELLULOID_BACKPORTED assigned to true and depreciation warning after.

As I understand this message shown up by default but it that case that note it Readme: "You can make the warning go away." is not valid as we can't :smile:

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
