### ISSUE TITLE
NoMethodError: private method `to_ary' called for #<Listener:0x007fc1b452fe90>

### ISSUE THREAD

**Issue by blanchma** [celluloid/celluloid#734]
I'm running Ruby 2.2 with celluloid (0.17.3). I get this error but I don't have a clue of the issue
NoMethodError: private method `to_ary' called for #<Listener:0x007fc1b452fe90>
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
E, [2016-11-24T14:18:55.195675 #55732] ERROR -- : Actor crashed!
Celluloid::DeadActorError: attempted to call a dead actor: respond_to?
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/responses.rb:29:in `value'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:4:in `respond_to?'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/mongoid-6.0.2/lib/mongoid/relations/referenced/many.rb:49:in `flatten'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/mongoid-6.0.2/lib/mongoid/relations/referenced/many.rb:49:in `<<'
	/Users/blanchma/workspace/concourse/lib/models/registration.rb:28:in `register_listener'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/mongoid-6.0.2/lib/mongoid/relations/proxy.rb:120:in `method_missing'
	/Users/blanchma/workspace/concourse/lib/models/execution.rb:71:in `register_listener'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/mongoid-6.0.2/lib/mongoid/relations/proxy.rb:120:in `method_missing'
	/Users/blanchma/workspace/concourse/lib/models/execution.rb:99:in `register_listener'
	/Users/blanchma/workspace/concourse/lib/models/execution.rb:93:in `add_message'
	/Users/blanchma/workspace/concourse/lib/scripts/script.rb:53:in `block in send'
	/Users/blanchma/workspace/concourse/lib/scripts/script.rb:96:in `execute'
	/Users/blanchma/workspace/concourse/lib/scripts/script.rb:51:in `send'
	/Users/blanchma/workspace/concourse/lib/scripts/ack_dim.rb:38:in `run'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/Users/blanchma/.rvm/gems/ruby-2.2.2@concourse/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
