### ISSUE TITLE
Unable to enable debug logging without $CELLULOID_DEBUG = true

### ISSUE THREAD

**Issue by mconigliaro** [celluloid/celluloid#742]
I tried this:

    Celluloid.logger.level = ::Logger::DEBUG

I also tried with my own logger:

    Celluloid.logger = ::Logger.new(STDERR)
    Celluloid.logger.level = ::Logger::DEBUG

But messages logged with `debug()` never appear. The only way I've been able to get debug messages is by setting `$CELLULOID_DEBUG = true`. Is this the intended behavior?

**Comment by mconigliaro** [comment]
I just discovered that calling `Celluloid.logger.debug()` instead of just `debug()` seems to work as expected.

**Comment by tarcieri** [comment]
Ugh, I should just get rid of those globals. So confusing...

**Comment by andy-twosticks** [comment]
Similar problem here -- I have a Logger object, but if I set Celluloid.logger to the logger object, it doesn't output anything.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
