### ISSUE TITLE
Wiki Conditions documentation signal vs broadcast

### ISSUE THREAD

**Issue by SpComb** [celluloid/celluloid#744]
The [Conditions Wiki page](https://github.com/celluloid/celluloid/wiki/Conditions) says:

> The call to condition.signal takes a single argument to return its results back to any tasks that are suspended in wait.
>
> Note that there may be multiple actors or methods waiting on the same Condition. A signal is broadcast to all of them.

But the actual [code](https://github.com/celluloid/celluloid/blob/v0.17.3/lib/celluloid/condition.rb#L65) has separate `signal` vs `broadcast` methods, where `signal` only appears to wake up one waiter, and it seems like you would need to use `broadcast` to get the behavior described in the wiki page?

```ruby
    # Send a signal to the first task waiting on this condition
    def signal(value = nil)
```

```ruby
    # Broadcast a value to all waiting tasks and threads
    def broadcast(value = nil)
```

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
