### ISSUE TITLE
From where to start a pool

### ISSUE THREAD

**Issue by Faisal-nfl** [celluloid/celluloid#746]
My pool will work for life time.
So from where to start the pool.
1 - If start on creating a new User, i.e main thread. main thread halts, and has to wait for the pool to finish work.
2- And Celluloid asks to avoid creating a pool with in an actor. so I can't create some new thread and call a async method in which to create pool.

So Where to create pool ?

**Comment by tarcieri** [comment]
The mailing list is the right place to ask (look like you already asked there)
