### ISSUE TITLE
I don't understand celluloid/culture and it's breaking my bundler

### ISSUE THREAD

**Issue by ioquatix** [celluloid/celluloid#755]
@digitalextremist can you please explain why this is necessary? It seems to make celluloid more complicated and even more of a "special snowflake" as it were. Sorry, it might be a great solution to some problem, I just don't get it.

**Comment by HoneyryderChuck** [comment]
@ioquatix are you talking about the submodule hell? I was under the impression that it was no longer present in the master branch.

**Comment by tarcieri** [comment]
Yeah, it's been removed from `celluloid/celluloid` master. We can remove it from the other Celluloid projects as well.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
