### ISSUE TITLE
Reconnecting ActiveRecord Inside Celluloid always fails.

### ISSUE THREAD

**Issue by meetme2meat** [celluloid/celluloid#771]
Chasing an issue where my Celluloid script is unable to reconnect to the database if, in case the connection gets lost.

Found [this discussion](https://groups.google.com/forum/#!searchin/celluloid-ruby/ActiveRecord%7Csort:date/celluloid-ruby/n9a1RpRztjY/P859mSPvBQAJ) around celluloid and ActiveRecord from 2011 but nothing in it that help me here.

Tested the AR reconnect under JRuby Thread, the reconnect works there.

Here are the scripts I used to test the reconnect thing ..

With script running Celluloid (`celluloid (0.17.1.1)`)

```

require 'celluloid'
require 'active_record'
require 'activerecord-jdbcpostgresql-adapter'

ActiveRecord::Base.establish_connection(adapter: 'postgresql', username: 'postgres', database: 'postgres', pool: 1, timeout: 10)

class Worker
  include Celluloid

  def start
    begin
      ActiveRecord::Base.connection_pool.with_connection do |conn|
         conn.execute('select pg_sleep(0.6);')
        conn.execute('select 1;')
        puts ".. Working .."
      end
    rescue Exception => exception
      puts "\n got exception #{exception.message}"
    end
  end
end

loop do
  Worker.new.async.start
  sleep 0.5
end
```

Using JRuby Thread.
```

require 'active_record'
require 'activerecord-jdbcpostgresql-adapter'
require 'securerandom'

ActiveRecord::Base.establish_connection(adapter: 'postgresql',username: 'postgres',database: 'postgres',encoding: 'unicode', pool: 1, timeout: 4)



loop do
  Thread.new() do
    Thread.current[:id] = SecureRandom.hex
    begin
      ActiveRecord::Base.connection_pool.with_connection do |conn|
        puts ".. #{Thread.current[:id]}"
        puts conn.to_s[0..75]
        conn.execute('select pg_sleep(0.6);')
        conn.execute('select 1;')
        puts "Working .. #{Thread.current[:id]}"
      end
    rescue Exception => exception
      puts "\ngot error from #{Thread.current[:id]} .... #{exception.message}\n"
    end
  end
  sleep 0.5
end
```
While I'm still searching for the reason for the above issue. Is anything specific I need to understand here.

**NOTE**: 
All code was tested under 
```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by zenmatt** [comment]
I have been troubleshooting the same issue without success.

**Comment by meetme2meat** [comment]
@zenmatt Anything that you can share here.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.

**Comment by dilumn** [comment]
Hi @meetme2meat sorry for the very late reply. 

I tried your script with Celluloid `0.18.0` & `0.17.1.1` today. Both gave me the same result

```
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..
.. Working ..

 got exception could not obtain a connection from the pool within 5.000 seconds (waited 5.002 seconds); all pooled connections were in use
.. Working ..

 got exception could not obtain a connection from the pool within 5.000 seconds (waited 5.003 seconds); all pooled connections were in use
.. Working ..
.. Working ..
```

Is this the exception you are referring to? Because `could not obtain a connection from the pool within 5.000 seconds` is not related to Celluloid as I understand here

I am using
```
gem 'activerecord', '~> 6.0.3'
gem 'activerecord-jdbcpostgresql-adapter', '~> 60.2', :platform => :jruby
```
&
```
java 11.0.2 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
```

**Comment by meetme2meat** [comment]
@dilumn well if it working then I'm good but as long as I remember it was not reconnecting the Database in celluloid but at the same time it was working perfectly with the traditional threading approach.

If I remember correctly I was not using 6.0.3 ActiveRecord it definitely some version 5 but not 6 so if it is working then I can close this issue.

**Comment by dilumn** [comment]
Thanks @meetme2meat feel free to reopen this again if you face the issue again
