### ISSUE TITLE
Restore culture repo for all those trying to get the bug fix

### ISSUE THREAD

**Issue by myers** [celluloid/celluloid#784]
I pull this out of my rubygems cache.

[culture.git.zip](https://github.com/celluloid/celluloid/files/2342434/culture.git.zip)

**Comment by myers** [comment]
@tarcieri this is what you requested in #779

**Comment by tarcieri** [comment]
Thanks, it's back up at https://github.com/celluloid/culture

**Comment by myers** [comment]
Thanks!
