### ISSUE TITLE
trying to use async method on a pool results in "undefined method for #<Celluloid::Supervision::Container::Pool"

### ISSUE THREAD

**Issue by rally25rs** [celluloid/celluloid#805]
Maybe I missed some detail here, but looking at https://github.com/celluloid/celluloid/wiki/Pools as an example, I have

a worker that I want to make a pool from
```
  require 'celluloid/current'

  class SampleJob
    include Celluloid

    def perform(a, b, c)
      ...
    end
```

I made a pool
```
    def sample_pool
      @sample_pool ||= SampleJob.pool
    end
```

and call it
```
sample_pool.perform!(1,2,3)
```

This results in
```
ERROR|2020-08-26 18:33:05.349|30811|exception_id=d0bfd9d6 exception_class=NoMethodError exception=undefined method `perform!' for #<Celluloid::Supervision::Container::Pool:0x1ff1990> backtrace=["/home/vagrant/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/celluloid-0.17.4/lib/celluloid/calls.rb:42:in `rescue in check'",
"/home/vagrant/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/celluloid-0.17.4/lib/celluloid/calls.rb:39:in `check'",
"/home/vagrant/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/celluloid-0.17.4/lib/celluloid/calls.rb:26:in `dispatch'",
"/home/vagrant/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/celluloid-0.17.4/lib/celluloid/call/sync.rb:16:in `dispatch'",
"/home/vagrant/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/celluloid-0.17.4/lib/celluloid/cell.rb:50:in `block in dispatch'",
"/home/vagrant/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/celluloid-0.17.4/lib/celluloid/cell.rb:76:in `block in task'",
"/home/vagrant/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/celluloid-0.17.4/lib/celluloid/actor.rb:339:in `block in task'",
"/home/vagrant/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/celluloid-0.17.4/lib/celluloid/task.rb:44:in `block in initialize'",
"/home/vagrant/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/celluloid-0.17.4/lib/celluloid/task/fibered.rb:14:in `block in create'",
"(celluloid):0:in `remote procedure call'",
"/home/vagrant/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/celluloid-0.17.4/lib/celluloid/call/sync.rb:45:in `value'",
"/home/vagrant/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/celluloid-0.17.4/lib/celluloid/proxy/sync.rb:22:in `method_missing'",
...
```

Am I just missing something, or has something changed that isn't covered by the linked wiki page?

Celluloid v0.17.4
Ruby 2.5.3

**Comment by rally25rs** [comment]
Nevermind, I had a `!` at the end of my method call. I got that from another person's blog post about Celluloid that seemed to be incorrect. Deleting the `!` fixed it.

**Comment by harsh183** [comment]
Were you using the site point tutorial? 

I think we were recently looking at fixing up `!` related functionality as well and there might be a pull request on that soon.

**Comment by p-vinayak** [comment]
As of now, bang methods are not how celluloid recognizes asynchronous methods (the wiki is outdated in that regard) . The correct way of calling methods asynchronously now would be using `sample_pool.async.perform(1, 2, 3)`. However, this is more than likely return a different error related to pool that we're currently, in the process of fixing. Hopefully a PR very soon.

If you'd like to work around this by yourself, you can add `require 'celluloid/pool'` in your code and this should give you the expected behavior when used with the `async` example shown above.

**Comment by p-vinayak** [comment]
Here's an example demonstrating `pool` and `async` usage.

```ruby
require 'rubygems'
require 'bundler/setup'

require 'celluloid/autostart'
require 'celluloid/pool'
require 'prime'

class PrimeWorker
  include Celluloid

  def prime(number)
    if Prime.prime?(number) 
      puts number
    end
  end  
end

pool = PrimeWorker.pool

(2..1000).to_a.map do |i|
  pool.async.prime i 
end

sleep 100
```

**Comment by rally25rs** [comment]
> pool.async.prime

Oh man, thank you so much for pointing out the `.async` I didn't have that in there, and didn't realize that it blocks the caller without it 🤦
