### ISSUE TITLE
Update docs related to using Pool

### ISSUE THREAD

**Issue by drakkhen** [celluloid/celluloid#811]
The wiki docs about using pools (https://github.com/celluloid/celluloid/wiki/Pools) needs to be updated to include the fact that, in version 0.18.x, you must require celluloid/pool explicitly:

https://github.com/celluloid/celluloid/blob/877053275a083c32b872addb1776e814cedb1d81/examples/pool.rb#L6-L7

In previous versions, a class that includes Celluloid will have a .pool method -- now, by default, it does not.

**Comment by harsh183** [comment]
Thanks for bringing this up! This was a recent change and we didn't update that just yet. Some of the older tutorials from the early 2010s I'm not sure we can update though.

Long story short the way things were implemented was really different and `pool` was done differently before so this was sort of merged it. 

Let me know if you have any issues.

**Comment by digitalextremist** [comment]
Closing @drakkhen, since you acknowledged @harsh183's solution. Please re-open this if you have trouble //
