### ISSUE TITLE
Pools not working: undefined method `services' for Celluloid:Module

### ISSUE THREAD

**Issue by d-Pixie** [celluloid/celluloid#812]
Running the basic test [from the documentation](https://github.com/celluloid/celluloid/wiki/Pools):

```
require "celluloid/pool"

class MyWorker
  include Celluloid

  def add_one(number)
    # roflscale computation goes here
    number + 1
  end
end

pool = MyWorker.pool

puts pool.add_one(5)
```

I get

```
 % ruby test.rb
Traceback (most recent call last):
	3: from test.rb:12:in `<main>'
	2: from /Users/someone/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/celluloid-0.18.0/lib/celluloid/supervision/container/behavior/pool.rb:13:in `pool'
	1: from /Users/someone/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/celluloid-0.18.0/lib/celluloid/supervision/supervise.rb:5:in `supervise'
/Users/someone/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/celluloid-0.18.0/lib/celluloid/supervision/supervise.rb:18:in `router': undefined method `services' for Celluloid:Module (NoMethodError)
Did you mean?  supervise
```

I'm on Os X Big Sur, tested with latest Truffleruby and MRI 2.7.1, same result on both, with celluloid 0.18.0

**Comment by dilumn** [comment]
@harsh183 do you have time to have a look?

**Comment by harsh183** [comment]
I'll take a look this weekend. Maybe it's just old documentation.

**Comment by digitalextremist** [comment]
That is a consequence of the gem reorganization, and revamp begun over the past year especially. `Celluloid` itself is not initialized properly. I would need to check the current state because `Pool` is being overhauled, but I would look at versions of gems, and require order at the top of the file. Documentation definitely needs to be updated too.

**Comment by harsh183** [comment]
Hey @davetron5000 , it took me some time but turns out there needed to be a 

```ruby
require "celluloid/autostart"
``` 

as well. I've updated the documentation to reflect this as well. 

Refer to this example as well on pool usage: https://github.com/celluloid/celluloid/blob/master/examples/pool.rb

**Comment by digitalextremist** [comment]
Closing this @d-Pixie, folliwing @harsh183's solution. Please re-open if this if you need more help on this //
