### ISSUE TITLE
difficulties with user interface during dvd playback

### ISSUE THREAD

**Issue by brainchild0** [celluloid/celluloid#814]
I have been experiencing some challenges in usability while playing DVD media. My use pattern  is to open a directory on persistent media that represents a capture of the files on a DVD, without any modification of format.

Following are some observations I have made:

- Forward and reverse jump cannot cross chapter boundaries. Once the boundary is reached,   repeated invocation of the action simply returns to the chapter boundary.
- When used near a chapter boundary, invocation of one of these actions often moves the playback position toward the direction opposite    of the action. For example, attempting to jump backward from the end of a chapter may actually move the position forward to the boundary of the next chapter.
- There is no indication of any keyboard shortcut for these actions, such as through a tooltip popup. (Ideally, the actions might be available not  only on the toolbar,  but also on the menu bar,  with shortcuts displayed.)

I am running Celluloid 0.21 on Cinnamon 5.2.6 with Linux Mint 20.3.

**Comment by dilumn** [comment]
Hi @brainchild0 looks like you are referring to another Celluloid project. Please reopen the issue with more details if the issue is related to Celluloid ruby gem
